### PR TITLE
Fixes #1615: Fix Test for Heroku Deployment

### LINKED ISSUE #1615: Fix Test unit to complete heroku deployment
- Issue type: Bug report 

### Short description

There is some change in Quora API data which is making Quora Profile Scraping test fail. For one returned value, the data keeps changing for most of the time and it should be removed.

### Environment

 - Operating system: Ubuntu 16.04 LTS
 - Software version: 
 - Software source: 

### Steps to reproduce

1.  Run ```./gradlew build```
2. 
3. 

### Expected behaviour

It should pass.
### Actual behaviour

It is failing.

### PR DESCRIPTION
**Pull request by simsausaurabh**
### Short description
I have:
- [X] There is a corresponding issue for this pull request.
- [X] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [X] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

Fixes: #1615

### CODE REVIEW

**Comment by simsausaurabh** [comment]
@singhpratyush It is there, but I already changed from previous value to the current deleted value and now it shows error for this too. I know the value which is required but it might get change in future too, so I removed it.

**Comment by singhpratyush** [comment]
I am sorry but I couldn't understand your previous comment at all. Could you please be more descriptive about it?

**Comment by simsausaurabh** [comment]
I sent a PR for fixing tests earlier too which got merged and the tests were running perfectly fine. But the change I made in the last PR for the currentImagePath in QuoraProfileScraperTest is changed again from Quora servers, so it is making test to fail again. So, it seems that the image path gets updated frequently from Quora servers, and hence I removed it.

**Comment by singhpratyush** [comment]
That doesn't seem correct. Please include the image path anyway and we must update it everytime Quora changes it. 

The task of tests is to let us know if our code fails somewhere. And when Quora changes the path, our code would fail. So the tests should let us know about this.

**Comment by simsausaurabh** [comment]
@singhpratyush I have added the new data of Image path instead of removing it. Please review again.

**Pull request merged**
