### PR TITLE
Add Python whitespace linting

### PR DESCRIPTION
**Pull request by SacredWKnight**
Require Python code has consistent whitespace according to PEP 8 style guideline.

### CODE REVIEW

**Comment by jig08** [comment]
@Orbiter Your thoughts on this pls ?

**Comment by Orbiter** [comment]
Hey SacredWKnight, what is this about? Please provide a description for your request.

**Comment by shivenmian** [comment]
@Orbiter I think this is for doing a codestyle check on the .py files. That's what flake8 does I think. But I'm not sure if this is required. @SacredWKnight can explain better.

**Comment by SacredWKnight** [comment]
@Orbiter @jig08 updated the description

**Comment by jig08** [comment]
@Orbiter Do we need this ?

**Comment by shivenmian** [comment]
I don't think so.

**Comment by jayvdb** [comment]
@SacredWKnight , can you rebase this to be sure there are no new violations of the enabled rules.

**Comment by shivenmian** [comment]
@jayvdb No problem, we can do a Squash and merge (from Github side) if this is to be merged.

**Comment by jayvdb** [comment]
@shivenmian, that would be foolish, and is bad software engineering.  Squash and merge will not fix it.  The only way to prevent a build breakage is to rebase, or to audit *all* changes since this patches' base to ensure they do not contain Python code and do not violate these rules.
There are four modified Python files since this patches' base, and **there are** new violations in those changes, so it *MUST* be rebased and revised before it is merged.

**Comment by shivenmian** [comment]
@jayvdb Sure, no problem :)

@SacredWKnight Could you please rebase your commits?

**Comment by sudheesh001** [comment]
@SacredWKnight Please rebase this and we're good to go.

**Comment by shivenmian** [comment]
@jayvdb @sudheesh001 I think this is good to merge now.

**Pull request merged**
