### PR TITLE
Correction in about.html

### PR DESCRIPTION
**Pull request by rkgudboy**
Tweets was wrongly mentioned as tsweets.

### CODE REVIEW

**Comment by rkgudboy** [comment]
@sudheesh001 done as you asked in this PR :)

**Comment by sudheesh001** [comment]
@rkgudboy Please mention `Fixes #271 Correction in about.html` as the git commit message, that way the issue automatically gets closed when this merges.

**Comment by Orbiter** [comment]
thank you!

**Comment by rkgudboy** [comment]
Thanks a ton for merging :)
I'll keep in mind the proper format in future.

**Pull request merged**
