### PR TITLE
Fixes #1431: Added Azure one click deploy

### LINKED ISSUE #1431: Introduce Azure one click for loklak
- Issue type: Feature request
Parent issue- #1311 

### Short description
At present loklak do not have Azure one click deployment button.
Add that feature.

More details about azure one click:
https://azure.microsoft.com/en-in/blog/deploy-to-azure-button-for-azure-websites-2/
https://elliotthamai.wordpress.com/2014/11/15/using-custom-arm-templates-with-the-deploy-to-azure-button/

I will work on this.

### PR DESCRIPTION
**Pull request by kavithaenair**
### Short description
Fixes #1431 

I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by mariobehling** [comment]
What is the status on this?

**Comment by kavithaenair** [comment]
@mariobehling, am working on this. I am facing a problem while testing the script. The example provided in Azure site for one click is also not working and showing up some error in the console, the error is seen while am running this script. I have figured out the problem, it will be done by today. Thank you.

**Comment by kavithaenair** [comment]
@vibhcool @singhpratyush @djmgit Please review
Deployment link: https://loklak-server0601.azurewebsites.net/

Screenshot for successful deployment:
image

**Comment by djmgit** [comment]
@kavithaenair  the test link is showing a blank page with this - You do not have permission to view this directory or page.

**Comment by kavithaenair** [comment]
@djmgit It was working fine for me. Anyways thanks for pointing it out. I'll look into it.

**Comment by kavithaenair** [comment]
@djmgit Please re-review.
New deployment id: http://13.82.190.72/

image

image

**Comment by kavithaenair** [comment]
@singhpratyush , as of now, it is not showing any charges yet. And no, I don't think so we are using kubernetes here.
These are the only configurations am giving as input:
image

You can try out the deploy to azure button from here.
https://github.com/kavithaenair/loklak_server/blob/azuretest/README.md

**Pull request merged**
