### PR TITLE
getParameter defined before using it in restpass.js

### PR DESCRIPTION
**Pull request by premshah**
### Short description
This is Issue : "getParameter' was used before it was defined (no-use-before-define)" in html/apps/resetpass/js/resetpass.js

I have resolved this issue

### CODE REVIEW

**Comment by premshah** [comment]
How to have a pull request of better quality??

Can you please help
@yukiisbored

**Comment by yukiisbored** [comment]
Myself and @jig08 already explained what you should do to improve this pull request. Please do it. If you have any questions or doubts, feel free to ask and talk about it in our gitter.

**Comment by mariobehling** [comment]
@premshah Thank you. Let's get this commit out of the queue. Please resolve the open issues.

And tell us: Which issue are you fixing? Please add the issue number into the description. 

Cheers.

**Comment by mariobehling** [comment]
Closing this PR. Please re-open if you plan to work on it again.

**Pull request closed without merging**
