### PR TITLE
Fixes #1531: NullpointerException due to no text in tweet

### LINKED ISSUE #1531: NullpointerException due to no text in tweet
- Issue type: Bug report

Some tweets doesn't have text. That is why this error occurs. 
```
2017-09-14 03:14:06.855:WARN :org.loklak.data.DAO$2:Thread-18: 
java.lang.NullPointerException
	at java.lang.StringBuilder.<init>(StringBuilder.java:112) ~[?:1.8.0_91]
	at org.loklak.harvester.TwitterScraper$TwitterTweet.enrichData(TwitterScraper.java:925) ~[loklak_server-all.jar:?]
	at org.loklak.harvester.TwitterScraper$TwitterTweet.enrich(TwitterScraper.java:918) ~[loklak_server-all.jar:?]
	at org.loklak.harvester.TwitterScraper$TwitterTweet.<init>(TwitterScraper.java:828) ~[loklak_server-all.jar:?]
	at org.loklak.data.DAO$SearchLocalMessages.<init>(DAO.java:1098) ~[loklak_server-all.jar:?]
	at org.loklak.data.DAO$SearchLocalMessages.<init>(DAO.java:1120) ~[loklak_server-all.jar:?]
	at org.loklak.data.Classifier.init(Classifier.java:175) ~[loklak_server-all.jar:?]
	at org.loklak.data.DAO$2.run(DAO.java:432) [loklak_server-all.jar:?]
```

### PR DESCRIPTION
**Pull request by vibhcool**
Fixes issue #1531 

### Short description
I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by vibhcool** [comment]
open for review

**Comment by vibhcool** [comment]
@sudheesh001 , yes we can tweet without text, see this https://api.loklak.org/api/search.json?q=from:vibhcool for my last tweet -> https://twitter.com/vibhcool/status/908711619378634753

**Comment by sudheesh001** [comment]
Perfect, can you add a check though for this, if text is `null/""` and picture(s) exists. Then do the rest of what you were doing already. Does that seem to be more appropriate for such a case? What do you think?

**Comment by vibhcool** [comment]
@sudheesh001 , we can add a test for this and a warn log in the code.

**Comment by sudheesh001** [comment]
Sure that's alright. Sounds good.

**Comment by vibhcool** [comment]
@sudheesh001 , in https://github.com/loklak/loklak_server/pull/1532 , I have added a try-catch block to test if any variable is null. There is no need to change in test. It tests the tweet text.

**Comment by mariobehling** [comment]
It seems reasonable to me. Let's see and iterate from here if required later.

Thank you!

**Pull request merged**
