### PR TITLE
Fixes #726 - Added initial set of Susi generic rules

### LINKED ISSUE #726: Add few generic rules to Susi
This issue aims at adding more generic questions which we come across daily chat, for example, 

- How was your day?

- How are things going on?

- How to deal with situations when I'm stressed? 

- I need some help 

- Susi please help me with my math. 

Currently these generic questions are being retrieved from urban dictionary or wikidata, but having a specific answer is useful and will increase the identity of Susi(we can make these rules to work by increasing the score).

### PR DESCRIPTION
**Pull request by daminisatya**
#726 
This PR aims at having high scored generic rules which avoids general definition retrieval from wikidata or Urban dictionary.

### CODE REVIEW

**Comment by jig08** [comment]
@daminisatya I believe this is good for starters. Squash the commits & we'll merge and we can add others later...

**Comment by daminisatya** [comment]
@jig08 Hopefully this is not blocking any other work item, currently adding some more. If so please let me know. Im not sure if this is a good rule set to start with cause there will be many others coming up. Currently I'm adding the commonly used ```conversations``` with Siri or Cortana before. Before merging it I wanted @Orbiter to give feedback once!

**Comment by mariobehling** [comment]
@daminisatya Which issue is this related to? Your comment should have been in the description at the beginning. Please do follow best practices now. Provide issues and details.

**Comment by daminisatya** [comment]
For squashing the commits im closing this PR, since i had few merge conflicts in between

**Pull request closed without merging**
