### PR TITLE
Fixes #345 - Implements IOT data servlet integrations into loklak

### LINKED ISSUE #345: Add IoT Services to Loklak
Add support for
* [x]  Weather information from US National Weather Service Reference: http://graphical.weather.gov/xml/
* [x] Thingsinspace, website data and info on https://github.com/jeyoder/ThingsInSpace
* [x] Public Transport Data An example of an interesting service is here: http://tracker.geops.ch, Technologies: http://geops.de/blog/technologien?language=en, Github is here: https://github.com/geops
* [ ] Airplane/Flight data, Websites like Flightradar (http://www.flightradar24.com) show plane data. There are resources that offer these data (apart from flightradars private/commercial data collection). The How to page (http://www.flightradar24.com/how-it-works) mentions the Federal Aviation Authority of the US for example (https://www.faa.gov/data_research/aviation_data_statistics/).
* [ ] Marine Traffic like http://www.marinetraffic.com/en/ais-api-services
* [ ] Data from EU Environmental Agency http://discomap.eea.europa.eu/home.html
* [x] Yet Another Haze Index (Yahi) http://rolandturner.com/yahi/ | http://rolandturner.com/yahi/developers | https://github.com/rolandturner/yahi
* [ ] Japan Radioactivity Map: http://japan.failedrobot.com/ | http://blog.safecast.org/data/
* [x] Freifunk-Karte http://www.freifunk-karte.de/ | https://github.com/ffansbach/nodelist
* [ ] Sahana Eden Disaster Management: E.g. http://nepal.sahana.io/eden/req/req
* [ ] Ebola Data Availability: http://eden.sahanafoundation.org/wiki/Deployments/Ebola#Data
* [ ] Data.org http://www.data.gov/developers/ | https://github.com/GSA/data.gov | http://ckan.org/features/
* [ ] German Open Data https://www.govdata.de
* [ ] Open Data Berlin: http://daten.berlin.de
* [x] Earthquake Data : http://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php
* [ ] Safecast Data: https://api.safecast.org/en-US/home
* [x] NMEA / GPS Devices Tracking Data: http://www.brickhousesecurity.com/category/gps+tracking/best+selling+tracking+devices.do

### PR DESCRIPTION
**Pull request by sudheesh001**
The commit solves the following IOT integrations
- Integration of the Earthquake data from US GOV.
- Scraping and Integrating the data from NOAA for live satellite weather alerts and base stations.
- Integrating the real time data from the YAHI Singapore to monitor Smog.
- Integrating the real time public router data from Freifunk Routers worldwide.
- Integrating the real time Things In Space data into loklak servers for out of world objects.
- Adds the JSONML file to the java org for markup level metrics and XML Validation to JSON Markup Language
- Earthquake data can be queried by magnitude and duration parameters live at 5 min harvest intervals

Please test and checkbox the following before any merges are performed.
- [x] Freifunk Router Data Fetch: http://localhost:9000/api/freifunkfetch.json
- [x] Earthquake Data Fetch: http://localhost:9000/api/earthquake.json?duration=month&magnitude=4.5 
```
1. http://localhost:9000/api/earthquake.json?duration=month&magnitude=4.5
2. http://localhost:9000/api/earthquake.json?duration=week&magnitude=4.5
3. http://localhost:9000/api/earthquake.json?duration=day&magnitude=4.5
4. http://localhost:9000/api/earthquake.json?duration=hour&magnitude=4.5

The different sets of magnitudes supported by USGS GOV EarthQuake Data sets are
1. Magnitude : <4.5, 2.5, 1.0, significant>
2. Duration  : <hour, day, week, month>
```
- [x] Yet Another Haze Index: http://localhost:9000/api/yahi.json
- [x] Stuff In Space Data Set: http://localhost:9000/api/stuffinspace.json
- [x] Key Value pairs of live Weather: http://localhost:9000/api/noaa.json
- [x] Check for the file `conf/iot/scripts/setup-noaa.pl` Running this file seperately should generate the files `conf/iot/scripts/states.xml` and `conf/iot/scripts/counties.xml` These files are being converted run through and mapped together as a `Key:Value` pair of the `state/county` and the required Link for the live data from there, to check if the data is correct remove the `&y=0` from the URL sample and check the live view on NOAA.

Please review carefully. We can leave any specific codacy issues as issues for contributors in GCI to take up just the same way we did it the last time.

### CODE REVIEW

**Comment by jig08** [comment]
@sudheesh001 The `codacy` checks seems to fail

**Comment by sudheesh001** [comment]
@jig08 As mentioned in the description
> Please review carefully. We can leave any specific codacy issues as issues for contributors in GCI to take up just the same way we did it the last time.

Did you check if the given test points i've mentioned are working ?
If you open codacy 3 issues are from the library and not worth fixing on our side, one is unavoidable.
```
protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
```
It complains on this about `Avoid really long methods.`

Coming to `Avoid calling finalize() explicitly` is needed in the NOAA Servlet because of the file handling it does and so garbage collections is necessary.

One definite thing that can be fixed is `Avoid unused imports such as 'org.json.JSONObject'` for Yahi and i'll do that

**Comment by sudheesh001** [comment]
@jig08 as mentioned, fixed. Left the library and the long methods.

**Comment by shivenmian** [comment]
Reviewing.

**Comment by shivenmian** [comment]
Tested everything, all works. Well done! :D

**Pull request merged**
