### PR TITLE
Added color & zooming to fit text for bubble charts

### LINKED ISSUE #444: Bubble charts text exceeds bubble
This is especially so for the small bubbles, where the text overlap with other bubbles

### PR DESCRIPTION
**Pull request by leonmak**
Fixes #444, where the text goes beyond the bubble, added zoom also and auto sizing the text, and number to the bubbles

### CODE REVIEW

**Comment by daminisatya** [comment]
@leonmak The "Most Mentions" chart seems to have broken names. Is there a on-Hover feature for viewing the full name ?

**Comment by leonmak** [comment]
Oh I set it to clip the text to fit the bubbles you can zoom in to see the mentions. I'll open another issue to make to the charts themselves responsive, so the bubbles can be bigger, as I've hard coded the svg size.

**Comment by mariobehling** [comment]
@leonmak Please provide screenshots for errors and for fixes for all issues.

**Comment by mariobehling** [comment]
@leonmak Please also assign all issues and add them into the right milestone. We are starting to loose track otherwise.

**Comment by leonmak** [comment]
@mariobehling sure, I also forgot about assigning and milestones for PRs, only did so for issues. I will add the screenshots too!

**Comment by leonmak** [comment]
screenshot 2016-05-27 22 01 09

**Pull request merged**
