### PR TITLE
Added initial LoginPage design

### PR DESCRIPTION
**Pull request by shivenmian**
Took up the SignUp page design and modified it. The design should be improved further but I wanted to get on with the accounts functionality first. Will definitely improve design of both Login and SignUp page once the system gets working. @Orbiter @daminisatya

### CODE REVIEW

**Comment by daminisatya** [comment]
@shivenmian Add a screenshot, and name it to screenshot.png (crop it to 640 x 640)

**Comment by shivenmian** [comment]
done @daminisatya

**Comment by daminisatya** [comment]
@shivenmian is this a separate app? I guess this should be integrated with the signup page. Or planing to keep it separate to add more functionalities?

**Comment by shivenmian** [comment]
The functionality of this and the signup page is different, so added this separately. Also, the app.json is different, so yeah.

**Comment by daminisatya** [comment]
Ok cool! Is this under review?

**Comment by shivenmian** [comment]
Yes will improve design later on but just want this merged to get started with the functionality

**Pull request merged**
