### PR TITLE
added loklak histogram visualization 

### PR DESCRIPTION
**Pull request by yasoob**
I hope you like this :+1: [Task](https://codein.withgoogle.com/dashboard/task-instances/6535414038921216/?sp-page=1)

### CODE REVIEW

**Comment by yasoob** [comment]
screenshot from 2016-01-17 22 19 23

**Comment by Orbiter** [comment]
oh wow! great work!

**Comment by yasoob** [comment]
Thanks :smile:

**Comment by yasoob** [comment]
I am working on [this](https://codein.withgoogle.com/tasks/5470699464425472/?sp-is_beginner=False) task :+1:

**Pull request merged**
