### PR TITLE
Fixes #1052 : fix username emoji in tweet

### LINKED ISSUE #1052: HTML appears on user's name when there is emoji
When querying on loklak server, in user's name, html text appears if name has emoji in it. When querying like this ->http://loklak.org/api/search.json?q=fossasia  , we get name field with value (if has emoji) with html string.

### PR DESCRIPTION
**Pull request by vibhcool**
this fixes the issue #1052

### CODE REVIEW

**Comment by vibhcool** [comment]
@yukiisbored Codacy is showing error in the line to change it's scoping and the way it has been declared. I have written this line the format other similar lines of code has been written. :)
Shall i make the changes?

**Comment by vibhcool** [comment]
@yukiisbored Shall I fix the issue in similar errors in the file according to codacy? However it shows error in 1 case only

**Comment by niccokunzmann** [comment]
@vibhcool Removing just this one issue will keep the code quality at the same level. I would merge it either way but if you like, you can just remove this and with it set an example on how to improve the others.
You can also remove the other issues. However, this would solve two problems in one pull-request which are unrelated. I would like to help but currently, I do not understand how to satisfy codacy.
What do you think?

**Comment by vibhcool** [comment]
yep :D , this issue #1070 ,is the solution to making the project codacy friendly and first timers friendly.

I think I shall fix codacy issue in the pr and rest problems could be solved later in other pr's.

**Comment by yukiisbored** [comment]
@vibhcool I don't merge red builds. Fix it.

**Comment by vibhcool** [comment]
Fixed and open for review :)

**Comment by vibhcool** [comment]
@jig08 yep , done :)

**Pull request merged**
