### PR TITLE
updated docker build badge

### PR DESCRIPTION
**Pull request by niccokunzmann**
I changed the url so github requests a new image.
The build works.
https://hub.docker.com/r/mariobehling/loklak/builds/

### Short description
I have:
- [ ] There is a corresponding issue for this pull request.
- [ ] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [ ] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by yukiisbored** [comment]
I don't see any different. In theory they're requesting the same thing. :/

**Comment by niccokunzmann** [comment]
True. But: https://github.com/niccokunzmann/dockerhub-build-status-image/commit/dcdd80400737076cdb355ced51385a99b0acaa9e#diff-3c2e0cb497179a8acc2e06609de60f98R113
was pushed in between. Now, the Github cache updates the badge every hour.

**Comment by niccokunzmann** [comment]
Currently, you see this: 
grafik
But the build is successful.

**Comment by yukiisbored** [comment]
Okay, I'll merge it just to trigger GitHub

**Pull request merged**
