### PR TITLE
[DO NOT MERGE] Added POST function

### PR DESCRIPTION
**Pull request by shivenmian**
Would want someone to test this, I'm not sure if this works. 

@Orbiter @daminisatya this posts the email and password to the servlet created in #485. The servlet returns a JSONObject which I'm parsing and displaying as an alert, just to test.

Does the code look fine or are there mistakes?

### CODE REVIEW

**Comment by daminisatya** [comment]
Is this for review?

**Comment by shivenmian** [comment]
Yes. Please see my commit and tell me if it's fine.

**Comment by shivenmian** [comment]
@daminisatya Just resolved a small error. See my commit now.

**Comment by shivenmian** [comment]
I think this requires a squash, sending a fresh PR.

**Pull request closed without merging**
