### PR TITLE
Fixes #1325: Add GithubScrapers and QuoraScrapers to SearchServlet

### LINKED ISSUE #1325: Add GithubScrapers and QuoraScrapers to SearchServlet
- Issue type: Feature request
- Parent Issue: #1231 

Tasks:

1) Configuration to use SearchScrapers from SearchServlet.
2) Set up GithubProfileScraper for SearchServlet.
3) Set up QuoraProfileScraper for SearchServlet.

### PR DESCRIPTION
**Pull request by vibhcool**
Fixes Issue #1325 

Test links:
- http://35.189.77.117/api/search.json?q=asd&scraper=quora
- http://35.189.77.117/api/search.json?q=asd&scraper=github
- http://35.189.77.117/api/search.json?q=asd&scraper=all_scraper
- http://35.189.77.117/api/search.json?q=asd&scraper=quora,github
- http://35.189.77.117/api/search.json?q=asd&scraper=quora&type=question
- http://35.189.77.117/api/search.json?q=asd&scraper=quora&type=user

`TODO`s:

1) get SourceType in application in DAO.java
2) add more scrapers

I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by vibhcool** [comment]
open for review
@Achint08 @djmgit @hemantjadon @kavithaenair @SKrPl @singhpratyush

**Comment by vibhcool** [comment]
@singhpratyush I will fix this :)

**Comment by vibhcool** [comment]
@singhpratyush , please re-review, made suggested changes

**Comment by singhpratyush** [comment]
@vibhcool: Could you please update the test links?

**Comment by vibhcool** [comment]
@singhpratyush updated the test links

**Comment by singhpratyush** [comment]
@vibhcool: http://35.189.77.117/api/search.json?q=day&source=cache&scraper=quora gives results. How is this possible if we are not pushing things to index?

**Comment by vibhcool** [comment]
@singhpratyush it is possible as only 2 get parameters are defined for this, scraper, q and other parameters of respective scrapers like type=question

it doesn't matter what other parameters are. it will matter in subsequent PRs :)

**Pull request merged**
