### PR TITLE
Fixes #286 404 page template and custom error handler

### LINKED ISSUE #286: Don't let 404s be the end of the road for the user.
404 pages are what users really hate, it'd be nice to ensure that these pages do not frustrate users with log failure messages but instead take the opportunity to put users in the right direction again. loklak server lacks a custom 404 page. I gave it a shot here. Image credits open clip art: https://openclipart.org/detail/171518/grasseating-cow

screen shot 2016-04-12 at 11 45 28 am

This is the initial attempt, I am open to more ideas about the text that could be used and the image. @mariobehling what do you think ?

@Orbiter I've read the jetty [custom error pages](https://wiki.eclipse.org/Jetty/Howto/Custom_Error_Pages) documentation but wasn't able to write the error codes with the `web.xml` file so that the server could automatically redirect to the 404 page if it hits the error.

Is the error handling happening here for the 404 pages too ?
```java
ErrorHandler errorHandler = new ErrorHandler();
errorHandler.setShowStacks(true);
servletHandler.setErrorHandler(errorHandler);
```

Can this be extended as documented here ?
> ## Custom error handler class
A context may be configured with a custom error handler class that extends either ErrorHandler for generic contexts, or ErrorPageErrorHandler for webapp contexts.
The following methods may be implemented to control the appearance of the error pages:
```java
void handle(String target, HttpServletRequest request, HttpServletResponse response, int dispatch) throws IOException
void handleErrorPage(HttpServletRequest request, Writer writer, int code, String message) throws IOException
void writeErrorPage(HttpServletRequest request, Writer writer, int code, String message, boolean showStacks) throws IOException
void writeErrorPageHead(HttpServletRequest request, Writer writer, int code, String message) throws IOException
void writeErrorPageBody(HttpServletRequest request, Writer writer, int code, String message, boolean showStacks) throws IOException
void writeErrorPageMessage(HttpServletRequest request, Writer writer, int code, String message, String uri) throws IOException
void writeErrorPageStacks(HttpServletRequest request, Writer writer) throws IOException
```

### PR DESCRIPTION
**Pull request by sudheesh001**
I need help to make the custom error handler redirect here when it hits a 404, looks like the web.xml isn't working as expected.

### CODE REVIEW

**Comment by shivenmian** [comment]
@sudheesh001 I'll try helping you on this. Should I merge and make changes?

**Comment by sudheesh001** [comment]
You can directly pull and work on this @shivenmian 
```
git checkout -b sudheesh001-CustomErrorHandler master
git pull https://github.com/sudheesh001/loklak_server.git CustomErrorHandler
```
Should bring you the updates

**Comment by shivenmian** [comment]
My GitHub is behaving weirdly, it's down atm, I will try it tomorrow and let you know @sudheesh001

**Comment by Orbiter** [comment]
why does this need a web.xml? Is it actually loaded? Where?

**Comment by sudheesh001** [comment]
@Orbiter That's right, i'll remove the web.xml file and squash this but could you tell me how to render the view file '/html/ERROR/404.html` instead of using `writer.write("No,no,no!!! This page does not exist!");`

**Comment by shivenmian** [comment]
It works, you can probably merge it.

**Pull request merged**
