### PR TITLE
Documenting Crawler/Parser Services 

### PR DESCRIPTION
**Pull request by jig08**
.. wrt https://github.com/loklak/loklak_server/issues/739

Sample view: [jig08/loklak_server/documentation-parsers/docs/parsers.md](https://github.com/jig08/loklak_server/blob/documentation-parsers/docs/parsers.md)

### CODE REVIEW

**Comment by daminisatya** [comment]
@jig08 very well written but there nothing ```Susi Su``` right? It's just ```Susi```

**Comment by jig08** [comment]
@daminisatya I remember @mariobehling saying something about her family name being _SU_

screenshot from 2016-07-23 10 33 56

**Comment by jig08** [comment]
@daminisatya Shall make changes.

**Comment by jig08** [comment]
@daminisatya Changes done. Commits squashed.

**Comment by daminisatya** [comment]
:+1:  well written!

**Comment by jig08** [comment]
@daminisatya Thanks :smiley:

**Comment by mariobehling** [comment]
Susi Su is just used in Facebook cause asksusi is not available. Wherever possible just use "Susi" only.

**Comment by jig08** [comment]
@mariobehling  Noted.

**Pull request merged**
