### PR TITLE
added search form :)

### PR DESCRIPTION
**Pull request by yasoob**

### CODE REVIEW

**Comment by yasoob** [comment]
screenshot from 2016-01-08 00 27 02

**Comment by Orbiter** [comment]
Hey, great work! Because the contributed search pages started to fill up the root path, I moved all contributions to a apps subfolder. Your contribution is now at http://localhost:9000/apps/yasoob/

**Comment by yasoob** [comment]
Thanks! :smile:

**Comment by mariobehling** [comment]
Looks great! How can I get search results? At the moment I don't see results here http://loklak.org/apps/yasoob/

**Comment by mariobehling** [comment]
Sorry, got it now, but it took 10+ seconds.

screenshot from 2016-01-08 18 58 43

**Pull request merged**
