### PR TITLE
Adding time and date service

### PR DESCRIPTION
**Pull request by jig08**
Sample link: [http://localhost:9000/api/console.json?q=SELECT%20*%20FROM%20timeanddate;](http://localhost:9000/api/console.json?q=SELECT%20*%20FROM%20timeanddate;)

screenshot from 2016-07-20 01 13 22

_EDIT_: ... wrt #732

### CODE REVIEW

**Comment by jig08** [comment]
Next: Adding the ability for SUSI to answer time and date related questions.

**Comment by shivenmian** [comment]
@jig08 travis is failing again. Your serviceimpl is wrong

**Comment by mariobehling** [comment]
@jig08 Which issue is it related to? Every PR needs to be related to an issue.

**Comment by treba123** [comment]
@jig08 :
Just change
`public JSONObject serviceImpl(Query call, Authorization rights, JSONObjectWithDefault permissions) throws APIException {`
to
`public JSONObject serviceImpl(Query call, HttpServletResponse response, Authorization rights, final JSONObjectWithDefault permissions)
			throws APIException {`

and it should build again :)

**Comment by jig08** [comment]
> @jig08 Which issue is it related to? Every PR needs to be related to an issue.

@mariobehling Here it is https://github.com/loklak/loklak_server/issues/732

**Comment by jig08** [comment]
@treba123 @shivenmian Thanks for the help, making the edit.

**Comment by jig08** [comment]
@shi Unfortunately, the IDE didn’t show any errors and it built successfully locally :smiley:

**Comment by jig08** [comment]
Fixes made, the build passes now.

**Comment by daminisatya** [comment]
Testing the changes.

**Pull request merged**
