### PR TITLE
Fixes #1103: Changed the URLs to the correct ones

### LINKED ISSUE #1103: Few URLs mentioned in documentation site are not working
- Issue type: Bug report 

### Short description
The urls mentioned for installation guide are redirecting to 404 error page.The urls mentioned in the documentation site are:
1. https://dev.loklak.org/installation_docker.html
2. https://dev.loklak.org/installation/installation_heroku.html
3. https://dev.loklak.org/installation/installation_cloud9.html
4. https://dev.loklak.org/development/eclipseSetup.html

### LINKED ISSUE #1108: Fix any spelling mistakes in documentation
- Issue type: Bug report

### Short description
```
### How do I setup loklak on Eclipse?

To install loklak on Eclipes, please refer to the [loklak Eclipse readme](/docs/development/eclipseSetup.md).
```

Markdown content in ReadMe contains the wrong spelling of `Eclipse` this needs to be fixed. A good easy beginner patch.

### PR DESCRIPTION
**Pull request by kavithaenair**
Fixes #1103  
Fixes #1108 

### Short description
I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [x] Reviewed this pull request by an authorized contributor.
- [x] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by kavithaenair** [comment]
@daminisatya @sudheesh001 @jig08 @mariobehling please review it.

**Comment by mariobehling** [comment]
@kavithaenair Please help us to make it easier for reviewers and add information of the issue into the description. I just did it here for you.

Please read this blog post how we try to work together: http://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/

Thanks.

**Comment by kavithaenair** [comment]
@mariobehling  yes i will try for a generic solution.

**Comment by mariobehling** [comment]
Thanks!

**Pull request merged**
