### PR TITLE
Fixes #1387: Remove TwitterTweet methods from MessageEntry Class

### LINKED ISSUE #1387: Remove TwitterTweet methods from MessageEntry Class
- Issue type: Feature request
- Parent Issue: #1365

MessageEntry Class can be used for other Scrapers to clean data and extract more data from scraped data.

 For this:
1) TwitterTweet's methods in MessageEntry class shall be removed.
2) MessageEntry shall be removed as SuperClass of TwitterTweet. (subsequent PR task)

Reference:-   

1) TwitterTweet is data object class of TwitterScraper . 
link: https://github.com/loklak/loklak_server/blob/12d7cda715f8e21238ee55b9cd5f69cfc9b8c14e/src/org/loklak/harvester/TwitterScraper.java#L656   

2) MessageEntry is superclass of TwitterTweet that holds supportive methods which are used in it. 
link: https://github.com/loklak/loklak_server/blob/a49728bb25feaf8d4f695fee4427b4a5adf8f984/src/org/loklak/objects/MessageEntry.java
--

### PR DESCRIPTION
**Pull request by vibhcool**
Fixes Issue #1387 

The changes have been made in:

1) TwitterScraper.java (main)
2) MessageEntry.java (main)
3) QueryEntry.java
4) SearchServlet.java
5) IndexEntry.java

In other programs, extra spaces have been removed due to `.editorconfig`.

Note: Please test the API calls related to TwitterScraper if they working perfectly

Test Link: http://35.190.235.2

I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by vibhcool** [comment]
@Achint08 @djmgit @hemantjadon @kavithaenair @SKrPl @singhpratyush : Please review

**Comment by vibhcool** [comment]
@djmgit , rebased

**Comment by singhpratyush** [comment]
@vibhcool: The deployment is not testable. Please update the link.

**Comment by Achint08** [comment]
@vibhcool Test link doesn't seem to work. Kindly check :)

**Comment by vibhcool** [comment]
@djmgit @Achint08 @singhpratyush , I have updated the image and tested it

**Pull request merged**
