### PR TITLE
Fixes issue #1212: Fix indentation

### PR DESCRIPTION
**Pull request by SarishiNoHara**
### Short description
Fixes issue #1212
I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by SarishiNoHara** [comment]
@vibhcool Thanks for review, just find a tiny problem and be familiar with PR processing, will do better code contribution later on.

**Comment by singhpratyush** [comment]
@SarishiNoHara: Can you look at the `checkstyle` issues for this file and improve the whole class instead?

You can find them in `build/reports/checksyle/main.html`.

**Comment by mariobehling** [comment]
@SarishiNoHara Create an issue, please! Follow our best practices for collaboration. http://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/

**Comment by vibhcool** [comment]
@SarishiNoHara , Please add fixes #<issue no.> in the title of PR and commit name

**Pull request merged**
