### PR TITLE
data/loklak.log as docker container output

### PR DESCRIPTION
**Pull request by niccokunzmann**
### Short description
I have:
- [x] There is a corresponding issue for this pull request.
- [ ] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [ ] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [x] The reviewer is assigned to the pull request.

Problem: I can not see the logs of the running loklak server in the docker image.

Solution: tail outputs the logs to the docker stdout from data/loklak.log.

This is discussed in issue #817.

### CODE REVIEW

**Comment by sudheesh001** [comment]
@niccokunzmann Can you amend the commit message as `Fixes #817 data/loklak.log as docker container output` ?

**Comment by niccokunzmann** [comment]
@sudheesh001 does it fix the issue?

**Comment by sudheesh001** [comment]
@niccokunzmann I think this should fix the problem of the logs appearing in the docker logs

**Comment by niccokunzmann** [comment]
@sudheesh001 done.

**Pull request merged**
