### PR TITLE
Displays proper url to open loklak_server during start and installation

### PR DESCRIPTION
**Pull request by SKrPl**
Solves issue: https://github.com/loklak/loklak_server/issues/1172

### Short description
I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by vibhcool** [comment]
@SKrPl error in travisCI build -> https://travis-ci.org/loklak/loklak_server/builds/233754489#L834

**Comment by SKrPl** [comment]
@vibhcool please check it now. Now the build is passing, last time it didn't because Travis couldn't download a gradle dependency, so the build didn't work.

**Comment by SKrPl** [comment]
@vibhcool done required changes.

**Comment by mariobehling** [comment]
@SKrPl Please ask other co-developers and assign them when you make a PR always. We need several reviews before we can merge. Please help to make this flow work.

**Comment by SKrPl** [comment]
@daminisatya  modified the commit message :smile:

**Pull request merged**
