### PR TITLE
Implement Settings page

### PR DESCRIPTION
**Pull request by yukiisbored**
`DAO` has been modified to be able to modify configuration.

A method to save the user configuration file has been added to
`LoklakServer`, and The method has been added to Loklak's Shutdown
Hook.

`SettingsServlet` has been modified and it's used as the backend API
for modifying and viewing the current server configuration. It can
only be accessed if the server was accessed via `localhost`.

`settings.html` and `settings.js` has been added as the front-end
loklak server configuration page which communicates with
`SettingsServlet` via a simple REST API that was mentioned before.

Closes https://github.com/loklak/loklak_server/issues/876

**Screenshot**:
The settings page
The apply button
success change
I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by yukiisbored** [comment]
Wait, let me fix the commit message first.

**Comment by mariobehling** [comment]
Thanks. Please provide a sample set up of a test system with the settings page and a screenshot.

**Comment by mariobehling** [comment]
@yukiisbored Does this make sense in order to get the settings systems rolling for the web?  - https://github.com/loklak/loklak_server/issues/919

**Comment by yukiisbored** [comment]
@mariobehling Yeah, it'll work. The only thing that modifies the settings is `POST` request for `/api/settings.json`. Still haven't looked into the `Account` thing that was mentioned, but to keep it simple regular HTTP login would be fine (and it makes it easier to implement it on the front end).

**Comment by yukiisbored** [comment]
@mariobehling I've added the screenshots you requested, I'll deploy the live system on Heroku.

**Comment by mariobehling** [comment]
@yukiisbored Ok, I am merging this. Please help to get the editing of settings limited to admins. Thank you!

**Pull request merged**
