### PR TITLE
Added Bluemix One-Click-Deployment Button

### PR DESCRIPTION
**Pull request by jig08**
Added the `One-Click-Deployment-Button` for **IBM Bluemix**. 
This works just fine at my end.

cc: @mariobehling @Orbiter @sudheesh001

### CODE REVIEW

**Comment by mariobehling** [comment]
This is fantastic! Well-done!

**Comment by sudheesh001** [comment]
I think this needs to be reverted. Depolyment is failing

screen shot 2016-05-03 at 9 23 04 am

Log
```log
Unable to find archive id for job input of job '7796dc76-0afe-4c82-b337-e3dff83b1a7d' on stage '7ad8b1cc-0d0f-403c-9b02-c35718e87a46'

Stage has no runtime information
```

**Comment by sudheesh001** [comment]
The build seems to work
```
Cloning the 'master' branch from repo 'https://P90MSG01:3041/git/dispensary/loklak-server-deploy-920'
Buildfile: /home/pipeline/427b84c1-1eff-4fa5-9af6-c8ba81285f49/build.xml

init:

build:
    [mkdir] Created dir: /home/pipeline/427b84c1-1eff-4fa5-9af6-c8ba81285f49/classes
     [echo] loklak: /home/pipeline/427b84c1-1eff-4fa5-9af6-c8ba81285f49/build.xml
    [javac] Compiling 128 source files to /home/pipeline/427b84c1-1eff-4fa5-9af6-c8ba81285f49/classes
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.

BUILD SUCCESSFUL
Total time: 6 seconds

Finished: SUCCESS
```
but the deployment results in failure. Could you please check it again @jig08 @mariobehling

**Comment by sudheesh001** [comment]
screen shot 2016-05-03 at 9 28 50 am

**Pull request merged**
