### PR TITLE
Fixes #1585: Temporary build files and directories getting tracked by git

### LINKED ISSUE #1585: Temporary build files and directories getting tracked by git
- Issue type: Bug report

### Short description

git is currently tracking unwanted temporary build files and folders. 

### Environment

 - Operating system: Ubuntu 16.04 LTS
 - Software version: 
 - Software source: 

### Steps to reproduce

1.  Run  ./gradlew build or do some changes to test files and run the build again. 
2.  Use vscode to run the project. 

### Expected behaviour

git should not track the temporary build files and directories.

### Actual behaviour

Temporary files and directories getting tracked by git.

### PR DESCRIPTION
**Pull request by simsausaurabh**
### Short description
I have:
- [X] There is a corresponding issue for this pull request.
- [X] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [X] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

Fixes: #1585

### CODE REVIEW

**Comment by simsausaurabh** [comment]
@singhpratyush please review.

**Comment by singhpratyush** [comment]
The files you mentioned never get generated on my side. How are they created?

**Comment by simsausaurabh** [comment]
These files have been created while writing new unit tests and updating older tests, and running them using ```./gradlew build```

screenshot from 2018-04-29 15-59-10

And ```.vscode/``` is being generated while running the project in vscode.

**Comment by sudheesh001** [comment]
Interesting, these file don't ever get generated for me either. Which IDE are you using? This patch can however be safely merged without any adverse impacts per se.

**Comment by sudheesh001** [comment]
Please rebase this branch to latest HEAD and push again to get the Travis Build to run. We can then merge this.

**Comment by simsausaurabh** [comment]
I am using vscode. And these files gets generated every time I build gradle.

**Comment by simsausaurabh** [comment]
@sudheesh001 Thanks, working on it :+1:

**Comment by simsausaurabh** [comment]
@sudheesh001 please review.

**Pull request merged**
