### PR TITLE
Added search1.pl script

### PR DESCRIPTION
**Pull request by yasoob**

### CODE REVIEW

**Comment by yasoob** [comment]
@mariobehling Can you kindly take a look at this PR? :)

**Comment by mariobehling** [comment]
Could you add a description and info which tasks this is. Cheers.

**Comment by yasoob** [comment]
[This](https://codein.withgoogle.com/dashboard/task-instances/4973797740380160/?sp-page=1) task! :+1:

**Comment by yasoob** [comment]
@mariobehling Could you kindly approve this pull request and take a look at [this issue](https://codein.withgoogle.com/dashboard/task-instances/4973797740380160/?sp-page=1)? :smile:

**Comment by Orbiter** [comment]
yeah! works perfectly! Thank you!

**Comment by yasoob** [comment]
Thanks! :)

**Pull request merged**
