### PR TITLE
Inserting Docker One-Click Deployment Button 

### PR DESCRIPTION
**Pull request by jig08**
[Demo Link](https://github.com/jig08/loklak_server/blob/master/README.md)

### CODE REVIEW

**Comment by sudheesh001** [comment]
@jig08 This looks good and seems to deploy correctly but I am not shown a public endpoint ! I have the following endpoint given to me http://loklak-1.loklak.8ccf2a5d.cont.dockerapp.io:32768/ but it somehow doesn't seem to be working with a running loklak, can you give me a link which is deployed on dockerapp ?

Also please squash the commits into one single commit.

**Comment by jig08** [comment]
@sudheesh001 

- The stack was created successfully.
```
Preparing to deploy...
loklak: Inspecting mariobehling/loklak:latest image in the registry
loklak: Image up to date in our database
loklak: Choosing best nodes...
loklak: Candidate node 7da470b7-f1ff-4afa-b079-8555ef9501d6.node.dockerapp.io. State: Deployed. Total num containers: 0. Num containers from this service: 0
loklak: Choosing node 7da470b7-f1ff-4afa-b079-8555ef9501d6.node.dockerapp.io because of the deployment strategy
Starting stack...
loklak: Deploying...
loklak-1: Deploying in 7da470b7-f1ff-4afa-b079-8555ef9501d6.node.dockerapp.io
loklak-1: Pulling image mariobehling/loklak:latest in 7da470b7-f1ff-4afa-b079-8555ef9501d6.node.dockerapp.io
loklak-1: Downloading layer 3960859f1259
loklak-1: Downloading layer 4c4dddd4ee84
loklak-1: Downloading layer 0612ff6b0e76
loklak-1: Downloading layer f214d4c55d23
loklak-1: Downloading layer d6bc70bb1f19
loklak-1: Downloading layer 39d208deefaa
loklak-1: Downloading layer f2e718485289
loklak-1: Downloading layer 3a4ac39acdc9
loklak-1: Downloading layer 44488ecde959
loklak-1: Downloading layer 2ecd8d1811b3
loklak-1: Downloading layer 9cadf697f7de
loklak-1: Downloading layer cb3f76ca3cae
loklak-1: Downloading layer 34adb5fcc5ff
loklak-1: Downloading layer fdc372ee7be7
loklak-1: Downloading layer e1cb63aa63e6
loklak-1: Downloading layer a54363020289
loklak-1: Downloading layer 76362f95660c
loklak-1: Downloading layer 52b0d9863b1c
loklak-1: Creating in 7da470b7-f1ff-4afa-b079-8555ef9501d6.node.dockerapp.io with docker name loklak-1.loklak.cbd7e1fb
loklak-1: Starting with docker id 4e1f935908561f4d9b157649aea5d10f57802a3111c6686121907b33bc3dd95f in 7da470b7-f1ff-4afa-b079-8555ef9501d6.node.dockerapp.io
loklak-1: Running in 7da470b7-f1ff-4afa-b079-8555ef9501d6.node.dockerapp.io
Stack Start action on 'loklak' has finished successfully
```

- Currently I do not have enough credits left in Digital Ocean , so I let Docker Cloud the localhost as a node to run containers.
```
2016-05-07T05:16:53.198801378Z starting loklak
2016-05-07T05:16:53.199042564Z loklak server started at port 9000, open your browser at http://localhost:9000
```

- As far as squashing the commits is considered, I totally agree it's a good practice to maintain a project, but now that GitHub provides a feature to squash 'em while merging the PR, I guess we could very well make use of that functionality :)

**Comment by sudheesh001** [comment]
I've tried it with both digital ocean and azure using dockercloud but as you pointed out, the deployment, build and running works perfectly fine but it doesn't provide a public URL endpoint, and the endpoint it gives isn't really working, what's the endpoint it's showing you ?

Coming to the issue about squashing, Github's squash and merge doesn't give a "merge" commit but instead rebases and merges similar to how Rultor.com does it, This isn't what we'd need, having a `merge` commit generated ensures that it's easy to revert to a particular commit in case of failures. and it can be done with ease because we know every merge is well tested and it was working at that point of time, also merges aren't counted by github as a personal commit. I hope that clarifies things and why we'd need a manual squash. https://groups.google.com/forum/#!searchin/astropy-dev/derived$20from$3A$20avoid$20github$27s$20new$20/astropy-dev/jA0l6XS-RVw/361BmVfuAQAJ

**Comment by jig08** [comment]
- I get [http://loklak-1.loklak.cbd7e1fb.cont.dockerapp.io:32768/](http://loklak-1.loklak.cbd7e1fb.cont.dockerapp.io:32768/) as the container endpoint.

- Okayy, I shall do the needful.

**Comment by sudheesh001** [comment]
The container endpoint doesn't seem to be running a loklak server, i've been facing the same issue that it doesn't go public. It'd be great if you could look through that, but since it works, i think it's okay to merge after a squash

**Comment by jig08** [comment]
Apologies for so many commits, erroneously added them and squashing is a pain now.
I have made a new PR https://github.com/loklak/loklak_server/pull/322 with a single commit.

**Pull request closed without merging**
