### PR TITLE
Fixes #1416: Deprecated Apache Ant in bluemix one click

### LINKED ISSUE #1416: Deprecate Apache Ant in bluemix one click
- Issue type: Bug report
Parent issue #1311 

### Short description
Deploy fails for bluemix one even after the change of buildpack, since pipeline.yml file uses `ant`

So, deprecate the ant build and use gradle.
I will fix this

### PR DESCRIPTION
**Pull request by kavithaenair**
### Short description
Fixes #1416 
Related to #1311 

I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by kavithaenair** [comment]
@singhpratyush @vibhcool Please review.

**Comment by singhpratyush** [comment]
@kavithaenair: Could you please post some screenshots/logs which reflects working of this patch?

**Comment by DengYiping** [comment]
A picture of successful build and a picture of failure during deployment process.


screen shot 2017-08-09 at 12 42 05 am

screen shot 2017-08-09 at 12 48 20 am

Crashes
screen shot 2017-08-09 at 12 49 00 am

screen shot 2017-08-09 at 12 52 29 am

screen shot 2017-08-09 at 12 53 43 am

**Comment by singhpratyush** [comment]
@DengYiping: From the first screenshot, it seems like you are still using `ant`. Please try to deploy using correct buildpack.

**Comment by DengYiping** [comment]
I will try it again. I pulled from your repo, should be the version with gradle.

**Comment by singhpratyush** [comment]
Look out for `.bluemix/pipeline.yml`. It contains the configurations.

**Comment by kavithaenair** [comment]
@DengYiping , you can only deploy successfully if this code gets merged into master branch. If not you should changingbutton configs and pipeline.yml file according to the branch of your repo.
Now the bluemix one click button uses ant build in loklak.

**Comment by DengYiping** [comment]
This time it is compiled with Gradle, but I faced the same problem again. Should I switch back to the old version of Gradle script(since I wrote the last one, I am pretty familiar with it)

screen shot 2017-08-09 at 1 51 25 am

screen shot 2017-08-09 at 1 52 29 am

screen shot 2017-08-09 at 1 52 38 am

screen shot 2017-08-09 at 1 55 34 am

I will try this script for one last time. This time I will pull it back to local, merge the bluemix branch and push to bluemix. If it still doesn't work, I suggest that we should start the debugging ASAP.

**Comment by DengYiping** [comment]
@kavithaenair  Last time I manually configured the pipeline to let it use Gradle. I thought of the branch problem also, so I am trying to merge it and try to deploy again.

**Comment by kavithaenair** [comment]
@DengYiping For heroku deployment, the tests were failing (you can see in #1394 ), after removing the tests it was working fine. You can check that as well.

**Comment by DengYiping** [comment]
After I looked into the log, the main problem was memory use during compilation. See:

screen shot 2017-08-09 at 2 25 01 am
screen shot 2017-08-09 at 2 23 21 am
screen shot 2017-08-09 at 2 23 49 am

Still, compilation is simple, but it is pretty hard to get it run on a machine with limited memory. It is not a wise idea to use IBM Bluemix free trial for loklak.

**Comment by kavithaenair** [comment]
@DengYiping free trail containers only provide 512MB but loklak needs 1GB.

**Comment by kavithaenair** [comment]
@DengYiping Is this script working fine except for the out of memory part?

**Comment by DengYiping** [comment]
@kavithaenair Yes, except out of memory problem, everything is just fine.

**Comment by kavithaenair** [comment]
@singhpratyush it's working fine for @DengYiping.  I think the script is working fine.

**Comment by djmgit** [comment]
@kavithaenair rebase !!

**Pull request merged**
