### PR TITLE
Generated a documentation site of loklak server, Fixes #895

### LINKED ISSUE #895: Generate a documentation site from the md files in a gh-pages branch
The idea is to have one stop resource for loklak tech questions at http://dev.loklak.org

Please autogenerate a simple documentation site on each new commit in the gh-pages branch.

There is already a site documenting java classes here http://loklak.github.io/loklak_server/

What is the best option to put the documentation together in one place?

### PR DESCRIPTION
**Pull request by adarsh-ideal**
Created a gh-pages site of loklak server which shows full documentation whereas the current repo of loklak search shows only java documentation.
For more information, check this issue: https://github.com/loklak/loklak_server/issues/895
Working site can be seen at: https://adarsh-ideal.github.io/loklak_server/

### CODE REVIEW

**Comment by mariobehling** [comment]
@Orbiter @adarsh-ideal How are the Javadocs generated? Will they be updated automatically still?

**Comment by adarsh-ideal** [comment]
Yes!
I have moved javadocs to a new separate folder named "java" and it can be updated automatically still.

**Comment by shivenmian** [comment]
This is fine, thanks.

**Comment by mariobehling** [comment]
Thanks. Right now I do not see, that the site gets updated automatically when someone makes changes in the development branch. Therefore I put up a follow up issue here https://github.com/loklak/loklak_server/issues/900

**Pull request merged**
