### PR TITLE
Add document explaining usage of streaming API

### LINKED ISSUE #1498: Add example of consuming the streaming servlets and stream APIs
Now that MQTT based streaming is available with Paho, please do add examples or apps about how to consume that information.

### PR DESCRIPTION
**Pull request by singhpratyush**
### Short description

Fixes #1498.

I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by singhpratyush** [comment]
@Achint08 @djmgit @hemantjadon @kavithaenair @SKrPl @vibhcool: Please review.

**Comment by singhpratyush** [comment]
@vibhcool: There is already an app which shows how to use the streaming feature. I, therefore, added a document instead.

**Comment by vibhcool** [comment]
Still, may be, a program with comments will be more helpful than example docs.

**Comment by singhpratyush** [comment]
@vibhcool: Please review again.

**Comment by djmgit** [comment]
@singhpratyush please check travis failure

**Comment by vibhcool** [comment]
@djmgit , travis failure is unrelated to PR

**Pull request merged**
