### PR TITLE
Add function for aggregation based on country codes

### LINKED ISSUE #1268: Add method for country based aggregation from classifiers
- Issue type: Feature request

### Short Description

Parent issue #1086.

The next step in classifier aggregation is making it location sensitive. The desired result is a method that can perform country-wise aggregation of results.

### PR DESCRIPTION
**Pull request by singhpratyush**
### Short description

Fixed #1268.

This PR introduces methods for country wise aggregations.

Following operations are now possible -
* All time aggregation for all countries
* Time sensitive aggregation for all countries
* All previous aggregations for selected countries

#### TODO
- [x] Allow for few countries only, instead of all.

I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by singhpratyush** [comment]
@Achint08 @djmgit @kavithaenair @SarishiNoHara @SKrPl @vibhcool: Please review.

Codacy shows error for an outdated diff, I have [updated it](https://github.com/loklak/loklak_server/pull/1270/files#diff-7e1c9703477f496ebb9e8301c8b01f23R1154) but the error still apears for previous version of the code.

**Comment by kavithaenair** [comment]
Please can you provide us with output screenshot or gist link to test it. @singhpratyush

**Comment by singhpratyush** [comment]
@kavithaenair: I wonder how can I show an output for this. I tested by adding hooks in `SearchServlet` (I know it's not a good practice, but works for testing the changes).

If you want, I can post that output here.

**Comment by kavithaenair** [comment]
@singhpratyush I think you can post the output in [here in pastebin](https://pastebin.ubuntu.com/) and paste the url in the description as sample output, so that others can also check that out.

**Comment by singhpratyush** [comment]
Code to check - 
```java
            ArrayList<String> classes = new ArrayList<>();
            classes.add("joy");
            classes.add("anger");
            ArrayList<String> countries = new ArrayList<>();
            countries.add("in");
            countries.add("us");
            printHashMap(DAO.elasticsearch_client.classifierScoreForCountry("messages", "classifier_emotion", classes));
            printHashMap(DAO.elasticsearch_client.classifierScoreForCountry("messages", "classifier_emotion", classes, "2016", "2017"));
            printHashMap(DAO.elasticsearch_client.classifierScoreForCountry("messages", "classifier_emotion", classes, "2016", "2017", countries));
            printHashMap(DAO.elasticsearch_client.classifierScoreForCountry("messages", "classifier_emotion", classes, countries));


    private void printHashMap(HashMap<String, HashMap<String, HashMap<String, Double>>> map) {
        StringBuilder sb = new StringBuilder();
        sb.append("----------\n");
        for (HashMap.Entry<String, HashMap<String, HashMap<String, Double>>> e1 : map.entrySet()) {
            sb.append(e1.getKey()).append("\n");
            for (HashMap.Entry<String, HashMap<String, Double>> e2 : e1.getValue().entrySet()) {
                sb.append("\t").append(e2.getKey()).append("\n");
                for (HashMap.Entry<String, Double> e3 : e2.getValue().entrySet()) {
                    sb.append("\t\t").append(e3.getKey()).append(" : ").append(e3.getValue()).append("\n");
                }
            }
        }
        System.out.println(sb.toString());
    }
```

Output - 
```
----------
de
	joy
		avg : 4.667079040001262E-7
		count : 609.0
		sum : 2.8422511353607684E-4
	anger
		avg : 1.3802612302300702E-8
		count : 164.0
		sum : 2.263628417577315E-6
au
	joy
		avg : 1.1086114586179697E-6
		count : 418.0
		sum : 4.6339958970231137E-4
	anger
		avg : 2.9537756306710344E-11
		count : 74.0
		sum : 2.1857939666965656E-9
in
	joy
		avg : 1.0741987258258922E-6
		count : 188.0
		sum : 2.0194936045526773E-4
	anger
		avg : 2.1288830867539278E-12
		count : 44.0
		sum : 9.367085581717282E-11
ph
	joy
		avg : 2.590592869734484E-8
		count : 317.0
		sum : 8.212179397058314E-6
	anger
		avg : 1.5059446880365558E-9
		count : 67.0
		sum : 1.0089829409844924E-7
GLOBAL
	joy
		avg : 7.91891261309384E-6
		count : 14962.0
		sum : 0.11848277051711005
	anger
		avg : 7.78330552992293E-8
		count : 3570.0
		sum : 2.778640074182486E-4
cm
	joy
		avg : 6.797206737561655E-8
		count : 373.0
		sum : 2.5353581131104975E-5
	anger
		avg : 2.8523579339361667E-10
		count : 120.0
		sum : 3.4228295207234E-8
gb
	joy
		avg : 5.279113544096412E-9
		count : 1283.0
		sum : 6.773102677075697E-6
	anger
		avg : 3.670574995835355E-7
		count : 281.0
		sum : 1.0314315738297347E-4
it
	joy
		avg : 4.206950621362695E-8
		count : 277.0
		sum : 1.1653253221174665E-5
	anger
		avg : 8.157537124833613E-8
		count : 70.0
		sum : 5.710275987383529E-6
fr
	joy
		avg : 1.0910749629625231E-8
		count : 567.0
		sum : 6.186395039997506E-6
	anger
		avg : 1.1141746221038508E-8
		count : 274.0
		sum : 3.0528384645645513E-6
us
	joy
		avg : 2.9719219899775024E-7
		count : 3060.0
		sum : 9.094081289331157E-4
	anger
		avg : 9.25431885895938E-9
		count : 647.0
		sum : 5.987544301746719E-6
nl
	joy
		avg : 5.389740298502135E-9
		count : 523.0
		sum : 2.818834176116617E-6
	anger
		avg : 7.326712423835978E-9
		count : 111.0
		sum : 8.132650790457935E-7

----------
de
	joy
		avg : 1.2431532373369554E-7
		count : 22.0
		sum : 2.734937122141302E-6
	anger
		avg : 2.514854012691486E-18
		count : 4.0
		sum : 1.0059416050765944E-17
au
	joy
		avg : 2.8860802276390966E-17
		count : 10.0
		sum : 2.8860802276390965E-16
	anger
		avg : 7.308902967443145E-14
		count : 1.0
		sum : 7.308902967443145E-14
in
	joy
		avg : 8.797212976203384E-16
		count : 7.0
		sum : 6.158049083342368E-15
ph
	joy
		avg : 5.585979331563391E-13
		count : 8.0
		sum : 4.468783465250713E-12
	anger
		avg : 1.9834114571634543E-17
		count : 2.0
		sum : 3.9668229143269087E-17
GLOBAL
	joy
		avg : 2.5187143683851033E-5
		count : 369.0
		sum : 0.00929405601934103
	anger
		avg : 2.5691127230472605E-8
		count : 85.0
		sum : 2.1837458145901714E-6
cm
	joy
		avg : 3.3733245008493517E-15
		count : 16.0
		sum : 5.397319201358963E-14
	anger
		avg : 4.5037916517753504E-10
		count : 4.0
		sum : 1.8015166607101401E-9
gb
	joy
		avg : 2.7926402939991637E-13
		count : 19.0
		sum : 5.306016558598411E-12
	anger
		avg : 1.4866875639596136E-11
		count : 9.0
		sum : 1.3380188075636523E-10
it
	joy
		avg : 1.7094825976318197E-16
		count : 11.0
		sum : 1.8804308573950017E-15
	anger
		avg : 1.2045941512599658E-11
		count : 2.0
		sum : 2.4091883025199316E-11
fr
	joy
		avg : 1.7123273527378921E-9
		count : 8.0
		sum : 1.3698618821903137E-8
	anger
		avg : 4.715849104194017E-14
		count : 3.0
		sum : 1.414754731258205E-13
us
	joy
		avg : 6.145826095856104E-10
		count : 90.0
		sum : 5.531243486270494E-8
	anger
		avg : 1.3427715673130153E-7
		count : 15.0
		sum : 2.014157350969523E-6
nl
	joy
		avg : 9.662363868430082E-16
		count : 14.0
		sum : 1.3527309415802115E-14
	anger
		avg : 7.060260117664472E-13
		count : 4.0
		sum : 2.8241040470657888E-12

----------
in
	joy
		avg : 8.797212976203384E-16
		count : 7.0
		sum : 6.158049083342368E-15
GLOBAL
	joy
		avg : 2.5187143683851033E-5
		count : 369.0
		sum : 0.00929405601934103
	anger
		avg : 2.5691127230472605E-8
		count : 85.0
		sum : 2.1837458145901714E-6
us
	joy
		avg : 6.145826095856104E-10
		count : 90.0
		sum : 5.531243486270494E-8
	anger
		avg : 1.3427715673130153E-7
		count : 15.0
		sum : 2.014157350969523E-6

----------
in
	joy
		avg : 1.0741987258258922E-6
		count : 188.0
		sum : 2.0194936045526773E-4
	anger
		avg : 2.1288830867539278E-12
		count : 44.0
		sum : 9.367085581717282E-11
GLOBAL
	joy
		avg : 7.91891261309384E-6
		count : 14962.0
		sum : 0.11848277051711005
	anger
		avg : 7.78330552992293E-8
		count : 3570.0
		sum : 2.778640074182486E-4
us
	joy
		avg : 2.9719219899775024E-7
		count : 3060.0
		sum : 9.094081289331157E-4
	anger
		avg : 9.25431885895938E-9
		count : 647.0
		sum : 5.987544301746719E-6
```

**Pull request merged**
