### PR TITLE
Adding time and date console service.

### PR DESCRIPTION
**Pull request by jig08**
Test link: [http://localhost:9000/api/console.json?q=SELECT * FROM timeanddate WHERE url='http://www.timeanddate.com/';](http://localhost:9000/api/console.json?q=SELECT%20*%20FROM%20timeanddate%20WHERE%20url=%27http://www.timeanddate.com/%27;)

screenshot from 2016-07-18 20 33 48

### CODE REVIEW

**Comment by jig08** [comment]
The next step is the addition of rules for _SUSI_ to answer date/time queries too.

**Comment by jig08** [comment]
NEXT: Rectify the build error:
```
[javac] /home/travis/build/loklak/loklak_server/src/org/loklak/api/search/TimeAndDateService.java:37: error: TimeAndDateService is not abstract and does not override abstract method serviceImpl(Query,HttpServletResponse,Authorization,JSONObjectWithDefault) in AbstractAPIHandler

    [javac] public class TimeAndDateService extends AbstractAPIHandler implements APIHandler {
    [javac]        ^
    [javac] /home/travis/build/loklak/loklak_server/src/org/loklak/api/search/TimeAndDateService.java:57: error: method does not override or implement a method from a supertype
    [javac] 	@Override
    [javac] 	^
```

**Comment by shivenmian** [comment]
@jig08 @Orbiter you dont need JSoup and an external site to get date and time. Just use

```Date date = new Date();``` and ```date.toString()``` gives you current date and time.

For timezone you can use ```Timezone.getDefault()```

**Comment by Orbiter** [comment]
Correct, don't use a remote service for that

**Comment by jig08** [comment]
@shivenmian @Orbiter Noted. Shall make a new console service regarding this keeping in mind the above.

**Pull request closed without merging**
