### PR TITLE
Add Cantonese test queries

### PR DESCRIPTION
**Pull request by wongalvis**
The words and phrases are found from Google Trends, extracts from passages and common words.

### CODE REVIEW

**Comment by DengYiping** [comment]
Good to see a comrade from China(or maybe HK) :)

**Comment by Orbiter** [comment]
Great, thank you!

**Comment by wongalvis** [comment]
@DengYiping I'm from Hong Kong :)

**Comment by DengYiping** [comment]
@wongalvis Great! I will come to HK in March to take the ACT.

**Comment by wongalvis** [comment]
@DengYiping Good luck!

**Pull request merged**
