### PR TITLE
Fixes #472: Categorize the apps display

### LINKED ISSUE #472: Add a category navigation to the applist app
Currently all apps are listed in one big list. We want to separate the list into categories. Each app has an category assignment. With https://github.com/loklak/loklak_server/commit/661e71253041ab4d9b1aec0d41d7860982e1c3f3 this assignment is used to add two more json objects to http://localhost:9000/api/apps.json:
```
  "categories": [
    "About project",
    "Demo",
    "Message Search",
    "Tweets analytics",
    "Message Visualizer",
    "Accounts API",
    "Peers API",
    "Suggestion Search",
    "Tweet search",
    "Users API"
  ],
  "category": {
    "About project": ["applist"],
    "Demo": [
      "barchart",
      "boilerplate",
      "bubblecharts",
      "tweetfeed"
    ],
    "Message Search": [
      "ducphanduy",
      "yasoob",
      "yathannsh",
      "zhidkovseva"
    ],
    "Tweets analytics": ["fossasia-histogram"],
    "Message Visualizer": ["histogram"],
    "Accounts API": [
      "loginpage",
      "signup"
    ],
    "Peers API": ["oneClickDeploy"],
    "Suggestion Search": ["querybrowser"],
    "Tweet search": ["social-wall"],
    "Users API": [
      "tweetsleaderboard",
      "userprofile"
    ]
  }
```
This shall be used to add a category navigation to the left column:
- remove the "Front-End contributions." hint on the left side
- list the 'categories' names in the left column as links. These links shall go to  ```/apps/applist/index.html?category=*category-name*```, i.e.  ```/apps/applist/index.html?category=Demo```
- if a link like ```/apps/applist/index.html?category=Demo``` is clicked, the app shall list only the app tiles from the requested category
- the "Read the loklak app primer to learn how you can contribute a loklak app!" hint shall be noted below the category list
- the category list shall be overwritten with the headline "Categories"
- make it beautiful!

### PR DESCRIPTION
**Pull request by daminisatya**

### CODE REVIEW

**Comment by Orbiter** [comment]
Your code has hard-coded categorization included. That is not the purpose. https://github.com/loklak/loklak_server/issues/472 shows exactly how to get categories from the /api/apps.json

**Comment by Orbiter** [comment]
your code should not contain this static configuration of the categories:
```
when("#AboutProject", { 
+        controller: "init('About project')",
+        activetab: "AboutProject"
+    }).
+    when("#Demo", {
+        controller: "init('Demo')",
+        activetab: "Demo"
+    }).
+    when("#MessageSearch", {
+        controller: "init('Message Search')",
+        activetab: "MessageSearch"
+    }).
+    when("#TweetsAnalytics", {
+        controller: "init('Tweets analytics')",
+        activetab: "TweetsAnalytics"
+
+    }).
+    when("#MessageVisualizer", {
+        controller: "init('Message Visualizer')",
+        activetab: "MessageVisualizer"
+    }).
+    when("#AccountsAPI", {
+        controller: "init('Accounts API')",
+        activetab: "AccountsAPI"
+
+    }).
+    when("#PeersAPI", {
+        controller: "init('Peers API')",
+        activetab: "PeersAPI"
+    }).
+    when("#SuggestionSearch", {
+        controller: "init('Suggestion Search')",
+        activetab: "SuggestionSearch"
+
+    }).
+    when("#TweetSearch", {
+        controller: "init('Tweet search')",
+        activetab: "TweetSearch"
+    }). 
+    when("#All", {
+        controller: "init('All')",
+        activetab: "All"
+    }).
+    when("#UsersAPI", {
+        controller: "init('Users API')",
+        activetab: "UsersAPI"
```
Please do a re-design

**Comment by daminisatya** [comment]
@Orbiter Working on refactoring it.

**Comment by Orbiter** [comment]
I reopened this for the new implementation

**Pull request closed without merging**
