### PR TITLE
Made it shorter and Python2+Python3 compatible

### PR DESCRIPTION
**Pull request by yasoob**
Made it shorter and Python2+Python3 compatible

### CODE REVIEW

**Comment by sudheesh001** [comment]
@yasoob How about having a look at the https://github.com/loklak/python-loklak-api#search-api

**Comment by yasoob** [comment]
Sorry. I am doing it for Google Code-in :) And the task specifically mentioned to modify this file. Kindly correct me if I am wrong.

**Comment by Orbiter** [comment]
This is actually much shorter. Why did you remove the "Requirements" comments? They are useful.

**Comment by yasoob** [comment]
Hi @Orbiter. In my opinion the requirements should be listed in the ```requirements.txt``` file. That way you can easily install them with one command as well. If you don't have the required package installed then you will get an error while running this script which will tell you what you are missing. Therefore, I don't think there is any need for the "requirements" comment here.

However, we can add it if you want. It won't hurt anyone if it is there :+1:

**Comment by Orbiter** [comment]
please add it in the same file.

**Comment by yasoob** [comment]
I have added it. :+1:

**Comment by sudheesh001** [comment]
@yasoob Can you squash this into one single commit ?

**Comment by yasoob** [comment]
@sudheesh001 I am doing just that :sparkles: In the mean-time why don't you mentor me on [this](https://codein.withgoogle.com/dashboard/task-instances/5187189314945024/?sp-page=1) task?

**Comment by yasoob** [comment]
I have squashed it. AND I have resubmitted the task for review as well. Would you mind taking another look at it?

**Comment by Orbiter** [comment]
thank you!

**Pull request merged**
