### PR TITLE
added query input in histogram app 

### PR DESCRIPTION
**Pull request by yasoob**

### CODE REVIEW

**Comment by Orbiter** [comment]
Thank you! I tested this, the page now provides an input box, but when I do a search I get the dialog box with "Kindly provide a query to search for!" - and no graphics. Tested with firefox.

**Comment by yasoob** [comment]
That is intentional. It gives that alert when there is no query in the
input field. If you want me to change it then i can change it.

I have got two ideas:

1. Automatically fill in the query input with loklak or fossasia on page
load.

2. Use loklak or fossasia as default input value when the input box is
empty and the user has clicked on plot.

Which approach do you like better?

**Comment by DengYiping** [comment]
@yasoob I think it is a bug in this web app. I just fixed it.

**Comment by yasoob** [comment]
@DengYiping Let me verify.

**Comment by yasoob** [comment]
Hey @Orbiter I just realized the issue. I have updated the code and submitted a [pull request](https://github.com/loklak/loklak_server/pull/233).

**Comment by DengYiping** [comment]
I've submit a pull request to fix the problem @yasoob . And I refactored your code.

**Comment by yasoob** [comment]
Hey @DengYiping Sorry but I didn't see your PR before. I will close mine. :+1:

**Pull request merged**
