### PR TITLE
Fixes #1503 Fixed markdown issues for yaydoc

### LINKED ISSUE #1503: Fix markdown issue for yaydoc
- Issue type: Bug report

### Short description

The documentation of this repo along with other FOSSASIA's repositories will be generated using yaydoc.
Some changes are needed in the markdown files so that they render properly on both github and yaydoc.

### PR DESCRIPTION
**Pull request by pri22296**
### Short description
- Removed scripts which published docs to dev.loklak.org repo.
- Made changes to markdown so that it renders properly on both github and yaydoc
- Removed README.rst as it's no longer needed.

Fixes #1503 

I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by pri22296** [comment]
@imujjwal96 @sch00lb0y Please review

**Comment by imujjwal96** [comment]
@pri22296  I think the second encryption key can be removed now

**Comment by imujjwal96** [comment]
https://github.com/loklak/loklak_server/blob/development/docs/development/api.md Is this table rendering? 
Can you show a sample deployment?

**Comment by pri22296** [comment]
@imujjwal96 Updated.

Preview : http://yaydoc.herokuapp.com/preview/priyamsingh.22296@gmail.com/0bf1c2c1-3bde-4eef-aabf-5beea653e0f8_preview/

> Is this table rendering?

Made changes for that.

**Comment by imujjwal96** [comment]
http://yaydoc.herokuapp.com/preview/priyamsingh.22296@gmail.com/0bf1c2c1-3bde-4eef-aabf-5beea653e0f8_preview/misc/architecture.html#the-file-system-structure A table here as well

**Comment by pri22296** [comment]
@imujjwal96 Updated

Preview: http://yaydoc.herokuapp.com/preview/priyamsingh.22296@gmail.com/004ec922-d60c-42ac-807b-071dc0ec19af_preview/misc/architecture.html

**Pull request merged**
