### PR TITLE
Fixes #694 Integrate TwitterAnalysis into Susi

### LINKED ISSUE #694: Integrate TwitterAnalysis app with Susi
@mariobehling @Orbiter The screenshots of the TwitterAnalysis app (#622) are [this](https://files.gitter.im/loklak/loklak/FLKG/Screen-Shot-2016-07-14-at-1.09.50-PM.png), [this](https://files.gitter.im/loklak/loklak/FAhj/Screen-Shot-2016-07-14-at-1.09.59-PM.png) and [this](https://files.gitter.im/loklak/loklak/3BYk/Screen-Shot-2016-07-14-at-1.10.07-PM.png). I implemented the app in #683. The app works fine and gives a lot of data.

Since this is a Twitter profile analyser, one can ask Susi a lot of questions which this servlet can answer. Questions like "in what tweet did @shiven_mian get max likes", "what is the average number of likes of @justinbieber", "in which month did @justinbieber tweeted the most", "at what time of the day does @justinbieber tweeted the most" and many more can be answered from the servlet. The answers to these questions can be particularly interesting as well because these are analytics.

I wish to integrate the app into susi and add rules for all possible questions that can be asked to Susi (which this servlet can answer).

### PR DESCRIPTION
**Pull request by shivenmian**
Added the PR back again.

### CODE REVIEW

**Comment by jig08** [comment]
@shivenmian Your rules work with _SUSI_ ?

**Comment by shivenmian** [comment]
No but I'm not sure I can do much about the scores not working with this PR.

**Comment by sudheesh001** [comment]
restarted build.

**Comment by shivenmian** [comment]
@sudheesh001 passes

**Pull request closed without merging**
