### PR TITLE
Fossasia push service

### PR DESCRIPTION
**Pull request by zyzo**
Implementation of Fossasia API push service, via /api/push/fossasia.json.

The implementation follows 2-steps mechanism described in #74 : validate & convert fields. This makes integration of future services trivial : only 2 json files are needed per service : 
  
* a json schema
* and a mapping file to map original fields to tweet fields, so that the message can be properly saved into back-end). 

If you look at FossasiaPushServlet.java, it's mostly "high-level code" that deals with request and response. All json manipulating logic is handled by the validation & conversion layer.

TODO : 
- [x] In conversion step, allow deep mapping (`name` -> `user.screen_name`). This is done before with parameter map_type of /api/push/geojson.json
- [x] FOSSASIA API Json file don't have mtime field. Currently, the id is computed from only two values : lat & lon, which is not a secure strategy. A proper way to compute id is needed.
- [ ] link api data to rich content https://github.com/loklak/loklak_server/issues/55#issuecomment-118917334
- [ ] save statistical information #35 
- [x] allow a source to contains multiple documents (array type)

### CODE REVIEW

**Comment by zyzo** [comment]
@Orbiter I have a question about the id computing strategy : is that true, that only ids from the same source are required to be different ? From an application point of view, messages from different sources, for e.g. TWITTER and FOSSASIA, with same ids cause no problem, since they can be distinguished by source_type. But I'm not sure how it works when saving to elastic db.

If this is true then I can just calculate the id based on lat & lon & community name. It is sure there's no two communities with the same name, located at the same area.

**Comment by mariobehling** [comment]
@zyzo For FOSSASIA communities I do not see that we could have that case - same name same location, but for other data (people, devices) it might be possible that you get the same name in the same location. The question is, if you need to stay generic here or not.

**Comment by Orbiter** [comment]
@zyzo 
> @Orbiter I have a question concerning id computing strategy : is that true, that only ids from the same source are required to be different?

no, all IDs must be unique, not only for a specific source

> From an application point of view, messages from different sources, for e.g. TWITTER and FOSSASIA, with same ids cause no problem, since they can be distinguished by source_type. But I'm not sure how it works when saving to elastic db.

we must make a source-prefix for the id, so they will be unique all the time.

> If this is true then I can just calculate the id based on lat & lon & community name. It is certain there's no two communities with the same name, located at the same area.

Lets consider the id as
`<source-domain>_<lon>_<lat>_<mtime>`
where mtime is the modification time that we must find out anyhow from the source. To prevent that we have a lot of doubles with same values, we must add a match there as well, but that is an add-on work.

**Comment by zyzo** [comment]
> where mtime is the modification time that we must find out anyhow from the source.

For sources that already have `mtime`, this is easy. For those who don't, a solution is to register the first mtime as the time when the message is first added. When adding later version of the message, compare the content with latest version, if the content changes, save the message, with new mtime value.

We could save & compare content hashes to reduce computing cost, like git does.

The problem is can we find the latest version of a message ? A.K.A is it possible to find a message by its partial id  `<source-domain>_<lon>_<lat>_` ?

**Comment by Orbiter** [comment]
> For sources that already have `mtime`, this is easy. For those who don't, a solution is to register the first mtime as the time when the message is first added. When adding later version of the message, compare the content with latest version, if the content changes, save the message, with new mtime value.

yes!

> We could save & compare content hashes to reduce computing cost, like git does.

If we compare the whole text part, then that would be the appropriate way to handle this, yes.

> The problem is can we find the latest version of a message ? A.K.A is it possible to find a message by its partial id  `<source-domain>_<lon>_<lat>_` ?

I planned to use the `<source-domain>` as screen_name with a special prefix, like `$<source-domain>`. Then it is easy to find the message by the screen_name and location_point.

**Comment by zyzo** [comment]
> I planned to use the <source-domain> as screen_name with a special prefix, like $<source-domain>. Then it is easy to find the message by the screen_name and location_point.

Actually, we have source_type that also identifies source domain (for FOSSASIA it's fossasia_api). I made the source_type a constraint (PR #59), which means it is searchable by source_type like this : q=/FOSSASIA_API, or q=-/TWITTER.

So we can find the message by source_type and location_point ?

**Comment by zyzo** [comment]
Also, for sources that already have id, should the format be `<source-domain>_<id>_<lon>_<lat>_<mtime>` ?

**Comment by zyzo** [comment]
This is good to merge. Two remaining tasks will be implemented in the same time with other push services.

**Comment by zyzo** [comment]
@Orbiter Could you help reviewing & merging this please ?

**Comment by Orbiter** [comment]
I just looked through your code and found very interesting concepts and a lot of code. Thank you for this work! This looks like it nicely fits into the overall structure of the application, so it was a perfect pull request.

**Comment by zyzo** [comment]
Thank you !

**Pull request merged**
