### PR TITLE
Allow time based aggregation in /api/classifier.json

### LINKED ISSUE #1266: Allow time based results for classifier.json endpoint
- Issue type: Feature request

### Short Description

Parent issue: #1086.
Related #1259 #1260.

As of now, the `/api/classifier.json` endpoint gives details about all possible messages. The desired result is that user should be able to fetch theses aggregations based on time of creation of Tweets.

### PR DESCRIPTION
**Pull request by singhpratyush**
### Short description

Fixes #1266.

Deployment link - http://104.154.80.218

Examples - 
* http://104.154.80.218/api/classifier.json?classifier=emotion&all=true&since=2017-06
* http://104.154.80.218/api/classifier.json?classifier=emotion&all=true&minified=true&since=2017-05&until=2017-06
* http://104.154.80.218/api/classifier.json?classifier=emotion&all=true&minified=true&since=2017-05-15&until=2017-06
* http://104.154.80.218/api/classifier.json?classifier=emotion&all=true&minified=true&until=2010-06
* http://104.154.80.218/api/classifier.json?classifier=emotion&all=true&minified=true
* http://104.154.80.218/api/classifier.json?classifier=emotion&all=true&minified=true&until=2017-06-23T12:00:00
* http://104.154.80.218/api/classifier.json?classifier=emotion&all=true&minified=true&until=2017

#### TODO
- [x] Add deployment link with examples

I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by singhpratyush** [comment]
@Achint08 @djmgit @hemantjadon @kavithaenair @SarishiNoHara @SKrPl @vibhcool: Please review.

**Comment by vibhcool** [comment]
could we handle this failure? http://104.154.58.246/api/classifier.json?classifier=emotion&all=true&until=2017-06-32
and I have doubt about date formats 2016-06 and 2017-06-23T12:00:00 in queries 😅

**Comment by singhpratyush** [comment]
@vibhcool: For allowed date formats, you can take a look at [format](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-date-format.html) of Elasticsearch.

And regarding the `500` error, I will add a `try-catch` block to the code.

**Comment by singhpratyush** [comment]
@vibhcool: Done with the changes - 
screenshot from 2017-06-25 19 32 27

I haven't updated the image on given deployment link so these changes will not be reflected there.

**Comment by kavithaenair** [comment]
@singhpratyush i think the test link isn't working.

**Comment by singhpratyush** [comment]
@kavithaenair: The server shut down unexpectedly yesterday. I'll update the deployment.

**Comment by singhpratyush** [comment]
@kavithaenair: Updated deployment link.

**Pull request merged**
