### PR TITLE
Added validation

### PR DESCRIPTION
**Pull request by shivenmian**
Added client-side validation in Sign Up page, which includes password matching (password = confirm password) and password strength. Need to add one more thing: matching email with database.

Have to write one more function, don't merge.

### CODE REVIEW

**Comment by mariobehling** [comment]
@shivenmian Please assign all issues and PRs to milestones and add Assignee. Which milestone is this PR in?

**Comment by shivenmian** [comment]
@mariobehling Sorry, I didn't know even PRs had to be assigned, only assigned milestones to issues. I've set it for Milestone 2 i.e this Sunday because I'll finish this in the next couple of hours.

**Comment by mariobehling** [comment]
Ok, thanks. As a reminder: https://groups.google.com/d/msg/loklak/ajzoqXfpdro/wDFY_3amCQAJ

Create Issues and PRs for All Work

- All created issues need to be assigned to one of the 15 milestones.
- All created issues need to be assigned to the person working on it.
- All PRs need to be associated to an issue.
- All PRs need to be assigned to one of the 15 milestones.
- All PRs need to be assigned to the person working on it.
- All PRs must pass all CI, Tests, Code Coverage, Code Quality.
- At the end of the week, the current milestone will close.
- All remaining opened issues must be reassigned to the next milestone.
- If an issue cannot be completed in less than a day, it should be broken up into multiple issues.
- Any unassigned issues and PRs will not be taken in account as part of GSOC.

**Comment by shivenmian** [comment]
@mariobehling Have both assigned myself and added milestones for [all my PRs](https://github.com/loklak/loklak_server/pulls?q=is%3Apr+author%3Ashivenmian) and [all my issues](https://github.com/loklak/loklak_server/issues?q=is%3Aissue+author%3Ashivenmian) till date. Will take care in the future too. Thank you. :D

**Pull request merged**
