### PR TITLE
Add search.html with tweets search

### PR DESCRIPTION
**Pull request by sevazhidkov**

### CODE REVIEW

**Comment by sudheesh001** [comment]
@sevazhidkov Great work ! I'll let @Orbiter review and merge.

**Comment by Orbiter** [comment]
Thank you, good work. I consider the task to be completed, however there is a small thing that you could add: when you typed is a search term, it is not possible to start the search by hitting 'enter'. You always have to click on the button. Can you add a fix so that it's just possible to hit on enter to search? Thank you!

**Comment by sevazhidkov** [comment]
Of course, made a new pull request with this feature

**Comment by Orbiter** [comment]
Hey, great work! Because the contributed search pages started to fill up the root path, I moved all contributions to a apps subfolder. Your contribution is now at http://localhost:9000/apps/zhidkovseva

**Comment by sevazhidkov** [comment]
Thank you. Can I help you with develop?

**Pull request merged**
