### PR TITLE
Heroku deploy

### PR DESCRIPTION
**Pull request by aneeshd16**
This PR adds a few changes to enable the deployment of Loklak server to Heroku.

1. LoklakServer.java (Please review): Added a conditional to check if the environment variable `PORT` is present. The server will be started with this port instead of 9000 or the port in config.properties. Heroku internally assigns a port to the app, and the app is expected to use this port for web deployment.
2. heroku_start.sh: Changed the process into a foreground one as Heroku requires foreground processes only. Also changed logging to stdout so that logs are visible in heroku logs.
3. Procfile: Defines the task to start. Required for deployment.
4. installation_heroku.md: Documentation for deploying to heroku

## Important
For testing this PR, instead of `git push heroku master`, you need to do `git push heroku heroku-deploy:master`

### CODE REVIEW

**Comment by aneeshd16** [comment]
@Orbiter please review the change in src/org/loklak/LoklakServer.java

**Comment by sudheesh001** [comment]
@aneeshd16 I am still having the application crashing on heroku as I push, any other changes ? Could you setup a heroku server and provide the link here ?

**Comment by aneeshd16** [comment]
@sudheesh001 http://loklak-heroku.herokuapp.com/
Is heroku build successful? If yes, then please post `heroku logs` here.
If not, what is the build error?

**Comment by aneeshd16** [comment]
@sudheesh001 Instead of `git push heroku master` you need to do `git push heroku heroku-deploy:master` for testing :smile:

**Comment by sudheesh001** [comment]
@aneeshd16 @Orbiter I think the changes in the LoklakServer.java file for PORT is fine and doesn't affect the overall functionality. from my side , its a (works for me) review+

I would like @mariobehling or @DengYiping to review this PR into a branch if possible, so that we could merge.

**Comment by aneeshd16** [comment]
bump. Can we go ahead with this?

**Comment by aneeshd16** [comment]
Since it doesn't affect present code or functionality, merging this.

**Pull request merged**
