### PR TITLE
overwriting of running process handled

### PR DESCRIPTION
**Pull request by SilentFlame**
@Orbiter  it handles all the three of your mentioned points for right behavior of the server in the #265 
@sudheesh001 ,
have a review, and issue #265 can be closed after this merge.

### CODE REVIEW

**Comment by SilentFlame** [comment]
@sudheesh001 can you please review it and merge it. 
as need your suggestion to make a restart.sh file or not.

**Comment by Orbiter** [comment]
oh wow thank you!

**Comment by SilentFlame** [comment]
@Orbiter  @sudheesh001 
I was thinking to make a `restart.sh` to quit and start the server again in one go, as it's annoying at the time of editing the code and running the `start` and `stop` again and again. It would be great to have that.
what's your say?

**Comment by Orbiter** [comment]
yeah thats useful but it should just be a stop.sh;start.sh

or not?

**Comment by SilentFlame** [comment]
ya that's what it is,
we can make a file with comments in between. 
`process with pid:XXXX shutting down, new process started on port : 9000`
something like this.

**Pull request merged**
