### PR TITLE
Add Gradle generated classes to the classpath

### PR DESCRIPTION
**Pull request by yukiisbored**
Some people may prefer to use Gradle over Ant to build Loklak so It's a
good idea to add Gradle's generated classes to the classpath of start.sh
and start.bat

### CODE REVIEW

**Comment by shivenmian** [comment]
It'd be great if you send one squashed PR with all the changes for #850, #851 and #852, not separate PRs with changes (since you sent these PRs at the same time and edited the same file).

Make PRs great again :)

**Comment by jayvdb** [comment]
@mariobehling , can this PR be re-opened. It fixes #873 , but it needs to be amended due to some whitespace issues.

**Comment by mariobehling** [comment]
It cannot be re-opened. @yukiisbored Please submit again.

**Comment by yukiisbored** [comment]
@mariobehling wait.

**Pull request closed without merging**
