### PR TITLE
FIXES  #1072: Solve returning link of images

### LINKED ISSUE #1072: API returns link of post instead of image that is in the tweet text
When we search for a keyword in loklak, it returns link of post having image (in tweettext) instead of image link

### PR DESCRIPTION
**Pull request by vibhcool**
The link loklak.org/api/search.json?q=fossasia returns links of posts of images instead of links of images. This PR solves this

### CODE REVIEW

**Comment by vibhcool** [comment]
@jig08 done and open for review
Thank you :)

**Comment by vibhcool** [comment]
@jig08 could you tell me the steps how to produce the output in /api/search.json , I am able to produce output in logs and by tracebacking the files but not in /api/search.json .

**Comment by niccokunzmann** [comment]
@vibhcool sadly, merge conflicts appeared. Would you like toremove them?

**Comment by vibhcool** [comment]
@niccokunzmann this issue was solved by @Orbiter with commit 209da109ec8bda66012a0566fb206dcdcebdfcfa , 
I have removed the merge conflicts, I don't know if this pr shall be merged

**Pull request closed without merging**
