### PR TITLE
🔍 Default values for description and link in rss

### PR DESCRIPTION
**Pull request by AdiChat**
🔍 This resolves the issue https://github.com/loklak/loklak_server/issues/828 by providing default vaues to description and link which is used in case, the fields are empty. This uses the title as the default description and http://loklak.org/ as the default link.

### CODE REVIEW

**Comment by jig08** [comment]
@AdiChat TravisCI build fails. Kindly rectify the error.

```
$ gradle assemble
:compileJava/home/travis/build/loklak/loklak_server/src/main/java/org/loklak/rss/RSSMessage.java:163: error: cannot find symbol
        if (link.length() > 0) this.map.put(Token.link.name(), link);
                ^
  symbol:   method length()
  location: variable link of type URL
/home/travis/build/loklak/loklak_server/src/main/java/org/loklak/rss/RSSMessage.java:163: error: incompatible types: URL cannot be converted to String
        if (link.length() > 0) this.map.put(Token.link.name(), link);
                                                               ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
2 errors
 FAILED
```

**Comment by shivenmian** [comment]
@AdiChat Please do an ant build before sending in PRs. This is a syntactical error.

**Comment by shivenmian** [comment]
@AdiChat Thanks.

**Comment by AdiChat** [comment]
@jig08 @shivenmian 
Thanks. I have updated the pull request.

**Pull request merged**
