### PR TITLE
Edited layout to select charts using tabs

### LINKED ISSUE #436: Include charts as partials in a single page
The user should be able to select a menu to see different charts instead of going to different pages, and also as many charts cannot fit on one screen at the same time

### PR DESCRIPTION
**Pull request by leonmak**
Fixes #436, allows user to select charts based on clicked tab, and select count attribute for search query

### CODE REVIEW

**Comment by mariobehling** [comment]
@leonmak Who is this assigned to? Which milestone is it?

**Comment by leonmak** [comment]
@mariobehling Sorry I forgot to mark my PRs, will do so from now on!

**Comment by leonmak** [comment]
screenshot 2016-05-27 21 59 52

**Comment by leonmak** [comment]
Currently has 2 tabs for 2 chart types
screenshot 2016-05-27 22 00 23
screenshot 2016-05-27 22 00 31

**Pull request merged**
