### PR TITLE
Fixes #1391: Heroku build pack updated

### LINKED ISSUE #1391: Add gradle buildpack for heruko deployment
- Issue type: Feature request
Parent issue #1311 

### Short description
As the ant build is deprecated replace it with gradle buildpack and test the heroku one click deploy button.
This will  successfully deploy the loklak server on heroku.

I will work on this.

### PR DESCRIPTION
**Pull request by kavithaenair**
### Short description
Fixes #1391 
Related to #1311 
This PR will now use gradle build for heroku one click deployment.

I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by kavithaenair** [comment]
@sudheesh001 @singhpratyush @vibhcool @djmgit @hemantjadon @Achint08  Please review.

**Comment by kavithaenair** [comment]
@singhpratyush Initially in heroku build was failing as it was using ant buildpack, now it is initiating the build, but failing at tests (strange because travis build is successful). But yes build is now using gradle pack.
As you can see below, it shows 27 tests completed , 2 failed (on herokuscreen):
image

It was successful in the console:
image

@singhpratyush you can try Deploy button from this branch:
https://github.com/kavithaenair/loklak_server/tree/heroku

**Comment by singhpratyush** [comment]
@kavithaenair: Try restarting the build again. Is there a way to define which tasks are executed for the buildpack so that tests are not executed while building the project on heroku?

```bash
gradle build -x test
```

**Comment by kavithaenair** [comment]
@singhpratyush Yes it working. 😄 
Deployment link: https://infinite-atoll-87251.herokuapp.com/

image

**Comment by mariobehling** [comment]
Good job.

**Pull request merged**
