### PR TITLE
Improved setup instructions for AWS

### PR DESCRIPTION
**Pull request by JLeow00**

### CODE REVIEW

**Comment by Orbiter** [comment]
thank you!

**Comment by DengYiping** [comment]
@JLeow00 Hello! Do you use a micro instance? Seem like my server on AWS is not stable and it crash couple time, do you face the same issue?

**Comment by JLeow00** [comment]
@DengYiping Yes I used a micro instance, but so far my server hasn't
crashed

**Comment by DengYiping** [comment]
@JLeow00 I have set up my AWS instance as backend, seem like I'm crawling too fast.

**Pull request merged**
