### PR TITLE
Updated buildpack URLs after naming convention changes

### PR DESCRIPTION
**Pull request by sudheesh001**
Test the following
- [ ] Heroku deploy
- [ ] Bluemix deploy
- [ ] Scalingo deploy

URLs have been changed for buildpacks from `aneeshd16/heroku-buildpack-ant-loklak` to `loklak/heroku_buildpack_ant_loklak` and similarly for bluemix for `leonmak/bluemix-buildpack-ant-loklak` to `loklak/bluemix_buildpack_ant_loklak`

### CODE REVIEW

**Comment by shivenmian** [comment]
@sudheesh001 I think it's better we merge it, test it, and if it doesn't work we revert. What say?

**Comment by sudheesh001** [comment]
Sounds alright logically it has to work, what you can try is , try git clone the url's if they work this should work too 😄

**Comment by daminisatya** [comment]
@sudheesh001 looks like minor changes you can squash your commits.

**Comment by sudheesh001** [comment]
Sure, I'll do

**Comment by daminisatya** [comment]
@sudheesh001 @shivenmian I'm merging it. Can you both test it?

**Pull request merged**
