### PR TITLE
Making EventBrite Crawler available in console ..

### PR DESCRIPTION
**Pull request by jig08**
.. wrt #671 

***

The request [http://localhost:9000/api/console.json?q=SELECT%20*%20FROM%20eventbrite%20WHERE%20url=%27url=https://www.eventbrite.com/e/?q=global-health-security-focus-africa-tickets-25740798421%27](http://localhost:9000/api/console.json?q=SELECT%20*%20FROM%20eventbrite%20WHERE%20url=%27url=https://www.eventbrite.com/e/?q=global-health-security-focus-africa-tickets-25740798421%27) leads to 

```
{
  "session": {
    "identity": {
      "type": "host",
      "name": "127.0.0.1",
      "anonymous": true
    }
  }
}
```

### CODE REVIEW

**Comment by shivenmian** [comment]
Don't think that should be the desired output, because that's only an authentication output which comes with every API call.

**Comment by jig08** [comment]
Currently, the sample link provided by @Orbiter [http://loklak.org/api/console.json?q=SELECT%20*%20FROM%20rss%20WHERE%20url=%27https://www.reddit.com/search.rss?q=loklak%2](http://loklak.org/api/console.json?q=SELECT%20*%20FROM%20rss%20WHERE%20url=%27https://www.reddit.com/search.rss?q=loklak%27) also yields similar results. 
I have just imitated the same for eventbrite crawler referring to the commit https://github.com/loklak/loklak_server/commit/6624d5902c9a442bc2cd4503491d1cf971f06e1d

**Comment by jig08** [comment]
@shivenmian @daminisatya  What result do you yield on calling [http://loklak.org/api/console.json?q=SELECT%20*%20FROM%20rss%20WHERE%20url=%27https://www.reddit.com/search.rss?q=loklak%27](http://loklak.org/api/console.json?q=SELECT%20*%20FROM%20rss%20WHERE%20url=%27https://www.reddit.com/search.rss?q=loklak%27) ?

**Comment by jig08** [comment]
Followed up in PR https://github.com/loklak/loklak_server/pull/676

**Pull request closed without merging**
