### PR TITLE
fixes #1184 - Instagram Profile Scraper is now working

### LINKED ISSUE #1184: Instagram Profile Scraper is not working
- Issue type: Bug report

### Short description
The scarper is showing (500) error message while searching for a profile.

screenshot 107

### PR DESCRIPTION
**Pull request by djmgit**
fixes issue #1184. Instagram scraper is now returning data.
I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [x] Reviewed this pull request by an authorized contributor.
- [x] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by djmgit** [comment]
insta

**Comment by djmgit** [comment]
@vibhcool @kavithaenair @SKrPl

**Comment by kavithaenair** [comment]
@djmgit please do ask before solving the issue. I was also doing the same.

**Comment by djmgit** [comment]
@kavithaenair my apologies, I shall do so from next time.

**Comment by singhpratyush** [comment]
@djmgit: Please share the link where this branch is deployed.

**Pull request merged**
