### PR TITLE
Add YAMLs for master deployment

### PR DESCRIPTION
**Pull request by singhpratyush**
### Short description

Related #1224.

Link - http://35.202.180.79/

I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by singhpratyush** [comment]
@Achint08 @djmgit @hemantjadon @kavithaenair @SKrPl @vibhcool: Please review.

**Comment by djmgit** [comment]
@singhpratyush squash your commits

**Comment by djmgit** [comment]
Also rebase!

**Comment by mariobehling** [comment]
What is the status of this PR?

**Comment by singhpratyush** [comment]
@mariobehling: The PR is ready from my side and I am waiting for reviews.

**Pull request merged**
