### PR TITLE
Create jars for distribution

### PR DESCRIPTION
**Pull request by cshubhamrao**

### CODE REVIEW

**Comment by sudheesh001** [comment]
Is it really necessary to include an extra  `/>` space as `_/>` where `_` is the space ? Maybe you could just include the `<target>` for the `jar` as you've written. Could you please redo this with only the changes  necessary rather than changing the formatting. This looks exciting, looking forward to this.

**Comment by cshubhamrao** [comment]
Ohk, maybe it was Eclipse's formatting, redoing the commit

**Comment by sudheesh001** [comment]
You added the `.jar` file too, i don't really think that's necessary, we can have .jar releases if needed. Please remove that from the commits.

**Comment by cshubhamrao** [comment]
.jar file requires the `html/` `conf/` and `lib/` dir also. Thats something to note. Releases will have to include those dirs also

**Comment by sudheesh001** [comment]
Please squash all commits into one place.

**Comment by cshubhamrao** [comment]
Commits squashed

**Comment by Orbiter** [comment]
good work, I moved the jar file to a dist subdirectory

**Comment by cshubhamrao** [comment]
It's not over yet. Here is what I think can be the method of distributing loklak:

* Modify `build.xml` further so that it creates a `release.zip` containing the following:
  * `conf/`, `lib/`,  `html/` directories.
  * Latest `loklak.jar` built by `ant`
* This `release.zip` will be uploaded to GitHub Releases.
* A python script (distributed as `.exe`) will do the following
 * Check presence of Java JRE, prompt user to download if absent.
 * Download the `release.zip` via GitHub API or other simpler means.
 * Extract the zip to a semi permanent location (My Documents?)
 * Run  the `.jar` 

Advantage is, only the python script will require tweaking, and same script can be used for other platforms too.

**Comment by sudheesh001** [comment]
We can use the `git tag` feature to keep releases and the changelog between releases. Sounds good @cshubhamrao

**Pull request merged**
