### PR TITLE
Update google cloud installation instructions

### PR DESCRIPTION
**Pull request by Elishanto**
### Short description
I have:
- [ ] There is a corresponding issue for this pull request.
- [ ] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [ ] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by niccokunzmann** [comment]
I am not authorized to merge but I agree with the content. It looks like you found some outdated descriptions and updated them. I would merge it.

**Comment by mariobehling** [comment]
Good job!

**Comment by Elishanto** [comment]
@mariobehling also please update link in GCI task description

**Comment by mariobehling** [comment]
Thanks. I updated it here: https://codein.withgoogle.com/tasks/5088620138463232/

Not sure, if there is another task with the link. Please let me know, if you find any. @niccokunzmann can also update things, if needed, I think.

**Pull request merged**
