### PR TITLE
Fix bug #265: Shutdown existing server

### PR DESCRIPTION
**Pull request by shivamMg**
Shutdown existing server before starting a new one.

### CODE REVIEW

**Comment by smokingwheels** [comment]
Is it possible to check the log for ports in use?
I had the problem where the elastic search had crashed and was tieing down the other ports, port 9000 was ok

**Comment by sudheesh001** [comment]
@shivamMg anything to say about the query put up by @smokingwheels ?
This looks good to me, but I'd let @Orbiter or @smokingwheels test this and merge.

**Comment by shivamMg** [comment]
Noted. 

`bin/start.sh` will first check for an existing server. If it exists it'll just display a message ("loklak already running") and exit.

I didn't notice other scripts before. The script `bin/checkalive.sh` seems to do the same, check if the server is up by making a call at localhost. But shouldn't the correct way to do this be checking for PID in `data/loklak.pid`. I get it that it also checks for "loklak" string from the "index.html" page, but still, there could be other servers running at localhost. 

Plus `bin/checkalive.sh` is doing what a restart.sh should be doing, check for conditions, kill the process and then starting it again. So you can't use `bin/checkalive.sh` in `bin/start.sh`, since it'll be doing a restart itself.

I think checkalive.sh should (only) have a function `is_alive` that just checks if the server is up. We can then source this script and use the function. A separate restart.sh should be created that essentially does what checkalive.sh is doing, i.e. killing and then starting the server.

@Orbiter What do you think?

**Comment by shivamMg** [comment]
@smokingwheels Sorry for the late reply. No, I checked the logs and they don't store the ports in use. Aren't the ports in use defined in the `conf/config.properties`, or in `customized_config.properties` if you have altered them. Or is there something I'm missing.

**Comment by Orbiter** [comment]
thank you for your code, however the behaviour is better if we do not kill existing processes just if you start another. The rule to take care of it was implemented in https://github.com/loklak/loklak_server/commit/bfa134f0b295f1fe8a53ad9f74cdefc0b1da9f83

**Pull request closed without merging**
