### PR TITLE
Fixes #1380: Add YoutubeScraper and WordpressCrawler to search endpoint

### LINKED ISSUE #1380: Add YoutubeScraper and WordpressCrawler to search endpoint
- Issue type: Feature request
- Parent issue: #1376 

The task:

1) Add YoutubeScraper to DAO.searchLoklak method so that it can be used from search.json endpoint.
2) Add WordpressCrawler to DAO.searchLoklak method so that it can be used from search.json endpoint.

### PR DESCRIPTION
**Pull request by vibhcool**
Fixes Issue #1380 
Example urls: 
1) http://127.0.0.1:9000/api/search.json?query=https://www.youtube.com/watch?v=xZ-m55K3FhQ&scraper=youtube
2) http://127.0.0.1:9000/api/search.json?q=http://blog.fossasia.org/this-api-or-that-library-which-one/&scraper=wordpress

I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by vibhcool** [comment]
@Achint08 @djmgit @hemantjadon @kavithaenair @SKrPl @singhpratyush : Please review

**Comment by vibhcool** [comment]
@kavithaenair , done :)

**Comment by SKrPl** [comment]
@vibhcool Can you please share the JSON output?

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Comment by djmgit** [comment]
@vibhcool please rebase!!

**Comment by kavithaenair** [comment]
@vibhcool squash your commits.

**Pull request merged**
