### PR TITLE
Fixes #915 Update TopMenuService.java

### LINKED ISSUE #915: Invalid Link
Clicking on Home,API,Architecture,Tutorials,Apps,Downloads in the nav-bar in loklak.org redirects to an invalid link, and gives the following error
image

### PR DESCRIPTION
**Pull request by pipix51**
### Short description
I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.
The corresponding issue for this pull request is #915. The problem why the navigation bar for the loklak.org website does not work lies in the Java file as the link to the specific section of the navbar is pushed onto the back of the current webpage link, causing duplicity and hence causing the link to be invalid, such as "http://loklak.org/http://loklak.org/about.html"

### CODE REVIEW

**Comment by yukiisbored** [comment]
Hey, Can you give us the `href` value for one of the menu items?

**Comment by pipix51** [comment]
The href value for about.html is http://loklak.org/about.html/
The extra slash is short for the original website, for example (http://loklak.org)/http://loklak.org/about.html, as the new address is appended to the original address; you could say this is similar to a file explorer.

**Comment by shivenmian** [comment]
I added full URLs because of [this issue](https://github.com/fossasia/apps.loklak.org/issues/7), which has now been fixed.

**Comment by pipix51** [comment]
The HTTP Error 404 still occurs (maybe a problem with gh-pages?) and I think since the issue is solved #915 can be closed.

**Pull request closed without merging**
