### PR TITLE
Related to #1439: Enhances the api.loklak.org page

### PR DESCRIPTION
**Pull request by kavithaenair**
### Short description
Related to #1439 

Demo link: http://35.184.207.233/

The tasks which are done:

- [x] Change "This is the Search Server for the Loklak Webclient hosting.." -> "This is the Open Source API Search Server for the Loklak Twitter and Social Media Search Engine hosting.."
- [x]  On Top Menu change "API" to api.loklak.org (itself) and delete api.html
- [x] Link "About" to http://loklak.org/about and delete about.html
- [x]  Change the following links
    - [x] http://api.loklak.org/about.html#whyuse -> http://dev.loklak.org/server/index.html#why-should-i-use-loklak
    - [x]  http://api.loklak.org/about.html#distributed -> http://dev.loklak.org/server/index.html#distributed-peer-to-peer
    - [x] http://api.loklak.org/api.html -> http://dev.loklak.org/server/development/api.html
- [ ]  Add the ico like in all other loklak sites
- [x]  Sort the menu items in the following order: About, Search, Blog, Developers, API
- [ ] Add a footer same as on loklak.org
        screenshot from 2017-08-12 01-29-30
- [ ] On the top left instead of using "loklak" as a text, add a "loklak cow logo" here and make the top bar disappear when a user scrolls up same as apps.loklak.org
- [ ] Use the same font as on apps.loklak.org for the top bar

I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by kavithaenair** [comment]
@vibhcool @djmgit Please review.

**Comment by mariobehling** [comment]
Please provide screenshots and a test setup link.

**Comment by kavithaenair** [comment]
@mariobehling 
Screenshot for the change:

image

I'll get back to you with the test link. Thank you.

**Comment by kavithaenair** [comment]
@mariobehling 
Screencast link:
https://www.screencast.com/t/cykCPSaFspbC

**Comment by mariobehling** [comment]
Please provide a link to a test setup.

**Comment by mariobehling** [comment]
The message  "Distributed Open Source Search Server for Twitter & Social Media" is too long. Please change it to "Distributed API Search Server for Twitter & Social Media".

**Comment by mariobehling** [comment]
Please tick what has been done:

* [ ] Change "This is the Search Server for the Loklak Webclient hosting.." -> "This is the Open Source API Search Server for the Loklak Twitter and Social Media Search Engine hosting.."
* [ ] On Top Menu change "API" to api.loklak.org (itself) and delete api.html
* [ ] Link "About" to http://loklak.org/about and delete about.html
* [ ] Change the following links 
   * [ ] http://api.loklak.org/about.html#whyuse -> http://dev.loklak.org/server/index.html#why-should-i-use-loklak
   * [ ] http://api.loklak.org/about.html#distributed -> http://dev.loklak.org/server/index.html#distributed-peer-to-peer
   * [ ] http://api.loklak.org/api.html -> http://dev.loklak.org/server/development/api.html
* [ ] Add the ico like in all other loklak sites
* [ ] Sort the menu items in the following order: About, Search, Blog, Developers, API
* [ ] Add a footer same as on loklak.org
screenshot from 2017-08-12 01-29-30
* [ ] On the top left instead of using "loklak" as a text, add a "loklak cow logo" here and make the top bar disappear when a user scrolls up same as apps.loklak.org
* [ ] Use the same font as on apps.loklak.org for the top bar

**Comment by kavithaenair** [comment]
@mariobehling Updated demo link and tasks done in PR description.

**Comment by mariobehling** [comment]
@kavithaenair Please finalize this PR and complete this issue entirely. I am unclear why are few html changes take several days and why you don't fulfill this PR entirely.

**Comment by kavithaenair** [comment]
@mariobehling I have completed 6 tasks out of 10. And other tasks are done by @djmgit in PR #1443

**Comment by mariobehling** [comment]
Ok, I am merging this, but honestly this task is too small to separate this between two people.

**Pull request merged**
