### PR TITLE
Reduce redundancy and code duplication on shell scripts

### PR DESCRIPTION
**Pull request by yukiisbored**
The shell scripts which are used to start/stop Loklak has a huge
amount of duplicate code. This commit reduces the amount of redundancy
and duplication by separating them into it's own script.

Fixes https://github.com/loklak/loklak_server/issues/886

### CODE REVIEW

**Comment by daminisatya** [comment]
@sudheesh001 Can you please have a look at this ?

**Comment by niccokunzmann** [comment]
This is a lot of code which you change. If you like to make a reviewer happy, you can try this in one PR each, notifying me and I can give you input

- Create the file where the duplicate code should go to, source this file in every bash script
- For each small duplication do:
    - delete from source file, put it into the new file

Also, you may want to look into functions, so the architecture can be decoupled from the use-cases (which does not need to be a good thing). Functions may make the code-reuse more obvious.

**Comment by yukiisbored** [comment]
Ok

**Comment by yukiisbored** [comment]
@niccokunzmann I've seperated the changes into multiple commits. I hope it's good to review.

**Comment by niccokunzmann** [comment]
I do not understand the last commit but I would merge the other commits. They are a joy to read. Really obvious what happens there.

**Comment by yukiisbored** [comment]
@niccokunzmann The last commit basically remove redundant code from `heroku_start.sh` and `bluemix_start.sh` by using `start.sh` with a couple of newly defined variables. Want me to revise the commit message?

**Comment by niccokunzmann** [comment]
If you remove the last commit, I will merge the ones before. Then, we can look at the last commit.
If you like: you call start.sh - It is clearer to pass arguments to start.sh than to crate variables for it.
This way, one can be sure that the arguments are only used in start.sh.

**Comment by yukiisbored** [comment]
@niccokunzmann I've changed from using variables to command arguments. I'm forced to use short single-characters flags because `getopt` is not available on macOS :(

**Comment by niccokunzmann** [comment]
Very nice! With getopt. I think, I merge it it looks good and a lot of work went into it.

**Pull request merged**
