### PR TITLE
Make homepage consistent with design scheme

### LINKED ISSUE #1466: Enhance site design and follow color design
1. Make the top bar appear/disappear more smoothly and when the user scrolls up make it appear again. Compare to http://chat.susi.ai and follow this approach.

2. Create a new section with a black background for the info about loklak "Nice? To get latest news about loklak," and Ensure it works on mobile screens

3. Please change colors of the site.

### PR DESCRIPTION
**Pull request by singhpratyush**
### Short description

Fix #1466.

Screencast - https://youtu.be/GMiykR7C-G8.

Screenshots - 

screenshot from 2017-08-18 02 35 18
screenshot from 2017-08-18 02 35 25
screenshot from 2017-08-18 02 35 34
screenshot from 2017-08-18 02 35 39
screenshot from 2017-08-18 02 38 30
screenshot from 2017-08-18 02 38 37
screenshot from 2017-08-18 02 40 13

I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by singhpratyush** [comment]
@Achint08 @djmgit @hemantjadon @kavithaenair @mariobehling @SKrPl @vibhcool: Please review.

**Comment by mariobehling** [comment]
* Please provide a test page.
* Why are the links in the gray area not anymore in the link color?
* Take out the the blue "follow" in front of accounts
* On the very end make everything simply in white font
* At the end show commit hash instead of commit message

**Comment by mariobehling** [comment]
When you post screenshot, please post the complete page, if the complete page is relevant. There are tons of plugins who take care of that for browsers.

**Comment by mariobehling** [comment]
What about the search box in the mobile page?

**Pull request merged**
