### PR TITLE
Additions for deploying to Heroku

### PR DESCRIPTION
**Pull request by aneeshd16**
This PR adds a few changes to enable the deployment of Loklak server to Heroku.

1. LoklakServer.java (Please review): Added a conditional to check if the environment variable `PORT` is present. The server will be started with this port instead of 9000 or the port in config.properties. Heroku internally assigns a port to the app, and the app is expected to use this port for web deployment.
2. heroku_start.sh: Changed the process into a foreground one as Heroku requires foreground processes only. Also changed logging to stdout so that logs are visible in heroku logs.
3. Procfile: Defines the task to start. Required for deployment.
4. installation_heroku.md: Documentation for deploying to heroku

### CODE REVIEW

**Comment by sudheesh001** [comment]
The steps seem to work fine but it's throwing an application error as follows
https://shrouded-fortress-44944.herokuapp.com/

```log
2016-02-07T08:17:52.651247+00:00 app[web.1]: sh: 0: Can't open bin/heroku_start.sh
2016-02-07T08:17:53.597972+00:00 heroku[web.1]: State changed from starting to crashed
2016-02-07T08:17:53.577475+00:00 heroku[web.1]: Process exited with status 127
2016-02-07T08:17:54.856175+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=shrouded-fortress-44944.herokuapp.com request_id=9b612790-ec04-45e5-bdb5-5743fac40f80 fwd="218.248.13.210" dyno= connect= service= status=503 bytes=
2016-02-07T08:17:56.554785+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=shrouded-fortress-44944.herokuapp.com request_id=4dcb859b-72f6-4300-8c0a-a5c012c4cb22 fwd="218.248.13.210" dyno= connect= service= status=503 bytes=
2016-02-07T08:17:58.855396+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=shrouded-fortress-44944.herokuapp.com request_id=7dedd17c-b9dd-4106-b7df-0674ca0917c1 fwd="218.248.13.210" dyno= connect= service= status=503 bytes=
2016-02-07T08:17:59.692230+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=shrouded-fortress-44944.herokuapp.com request_id=135401c8-7583-44ad-8b2d-f1c606122bac fwd="218.248.13.210" dyno= connect= service= status=503 bytes=
2016-02-07T08:19:02.955286+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=shrouded-fortress-44944.herokuapp.com request_id=fe9f4faa-d62c-4f14-a3ea-af001c139c22 fwd="218.248.13.210" dyno= connect= service= status=503 bytes=
2016-02-07T08:19:03.842269+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=shrouded-fortress-44944.herokuapp.com request_id=4ba442e5-52e2-4ea5-8db7-2b33601268f1 fwd="218.248.13.210" dyno= connect= service= status=503 bytes=
2016-02-07T08:22:46.367140+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=shrouded-fortress-44944.herokuapp.com request_id=78a7fea1-48b8-45e9-b0a1-f12c28a3b048 fwd="218.248.13.210" dyno= connect= service= status=503 bytes=
2016-02-07T08:22:47.090110+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=shrouded-fortress-44944.herokuapp.com request_id=8a38f939-c2c9-4849-962c-a8f2caaad4b7 fwd="218.248.13.210" dyno= connect= service= status=503 bytes=
```

**Comment by aneeshd16** [comment]
@sudheesh001 that file bin/heroku_start.sh is not present. Try cloning from here https://github.com/aneeshd16/loklak_server

**Comment by sudheesh001** [comment]
@aneeshd16 I've pulled this patch onto a new branch and then pushed it, even making changes and committing says `Everything is upto date`

**Comment by aneeshd16** [comment]
@sudheesh001 see #255

**Pull request closed without merging**
