### PR TITLE
Related to #1439 - Enhancing api.loklak.org page

### PR DESCRIPTION
**Pull request by djmgit**
Fixes part of #1439. Changes made:

* Add the ico like in all other loklak sites
* Add a footer same as on loklak.org
* On the top left instead of using "loklak" as a text, add a "loklak cow logo" here and make the top bar disappear when a user scrolls up same as apps.loklak.org
* Use the same font as on apps.loklak.org for the top bar

### Short description
I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by djmgit** [comment]
Test link: http://35.184.18.54/

@kavithaenair @vibhcool open for review

**Comment by kavithaenair** [comment]
@djmgit check codacy issue.

**Comment by mariobehling** [comment]
Provide screenshot and test deployment with each PR. Let's follow the guidelines in the third term.

**Comment by mariobehling** [comment]
I am unclear why a very simple issue needs to be split up into smaller parts.

**Comment by mariobehling** [comment]
Please solve this issue entirely. Mark what has been done already, please:

* [ ] Change "Distributed Social Media Message Search Server" to "Distributed API Search Server for Twitter & Social Media"
* [ ] Change "This is the Search Server for the Loklak Webclient hosting.." -> "This is the Open Source API Search Server for the Loklak Twitter and Social Media Search Engine hosting.."
* [ ] On Top Menu change "API" to api.loklak.org (itself) and delete api.html
* [ ] Link "About" to http://loklak.org/about and delete about.html
* [ ] Change the following links 
   * [ ] http://api.loklak.org/about.html#whyuse -> http://dev.loklak.org/server/index.html#why-should-i-use-loklak
   * [ ] http://api.loklak.org/about.html#distributed -> http://dev.loklak.org/server/index.html#distributed-peer-to-peer
   * [ ] http://api.loklak.org/api.html -> http://dev.loklak.org/server/development/api.html
* [ ] Add the ico like in all other loklak sites
* [ ] Sort the menu items in the following order: About, Search, Blog, Developers, API
* [ ] Add a footer same as on loklak.org
screenshot from 2017-08-12 01-29-30
* [ ] On the top left instead of using "loklak" as a text, add a "loklak cow logo" here and make the top bar disappear when a user scrolls up same as apps.loklak.org
* [ ] Use the same font as on apps.loklak.org for the top bar

**Comment by mariobehling** [comment]
Cow on top left is out of proportion and has strange light gray surrounding. Why? Please pay more attention to detail.

**Comment by djmgit** [comment]
@kavithaenair Thanks for suggesting that. I am using that image.
@mariobehling I have updated the top-left image.

**Comment by mariobehling** [comment]
Thanks.

A small change request: Please add "Apps" with a link into the top bar as well.
* Sort the menu items in the following order: About, Search, Apps, Blog, Developers, API

**Comment by djmgit** [comment]
@mariobehling sure

**Comment by djmgit** [comment]
@mariobehling did the changes

**Comment by mariobehling** [comment]
@singhpratyush Good point. We should follow up in the next issue on this.

Cheers.

**Comment by mariobehling** [comment]
@djmgit Please follow up here: https://github.com/loklak/loklak_server/issues/1438

**Comment by singhpratyush** [comment]
Created #1458 for topbar issue.

**Pull request merged**
