### PR TITLE
Susi: UI enhancements and rules addition

### PR DESCRIPTION
**Pull request by daminisatya**
Removed the stale chat. 
selection_189

### CODE REVIEW

**Comment by daminisatya** [comment]
selection_190

Changed the scroll and padding of the background container. 
Changed the color contrasts.

**Comment by shivenmian** [comment]
You could possibly add Enter to send and Shift-Enter to add new line in chatbox.

**Comment by daminisatya** [comment]
@shivenmian Enter to send key action is already there, was thinking on what key can be used to add a new line.

**Comment by shivenmian** [comment]
Is Enter to send working? I tried some time back after @sudheesh001 merged his commit, it wasn't working.

Use Shift-Enter to add new line, this combination is used almost everywhere.

**Comment by daminisatya** [comment]
Ok will use the shit enter code for adding new line.
"```Enter``` to send" is working

**Comment by shivenmian** [comment]
@daminisatya tested, the UI change looks fine to me.

**Pull request merged**
