### PR TITLE
Add Gradle build support and utility shell script for gradle. 

### PR DESCRIPTION
**Pull request by DengYiping**
Add Gradle build support and utility shell script for gradle. Shell
script is for compatibility with Ant.

### CODE REVIEW

**Comment by sudheesh001** [comment]
@DengYiping Looks good, Can you also add the gradle installation to the readme documentation.

**Comment by DengYiping** [comment]
@sudheesh001  You mean `brew install gradle`?

**Comment by sudheesh001** [comment]
Not just mac specific, Lets add the info for the linux and windows too ? but mac would be a good place to start

**Comment by DengYiping** [comment]
I do not have any Windows machine. It should be a similar task. I create a new pull request here.https://github.com/loklak/loklak_server/pull/227 so I am going to close this PR.

**Pull request closed without merging**
