### PR TITLE
Service for current date and time

### PR DESCRIPTION
**Pull request by jig08**
... in partial fulfillment of issue #748 

Sample Link: [http://localhost:9000/api/console.json?q=SELECT * FROM currentdateandtime;](http://localhost:9000/api/console.json?q=SELECT%20*%20FROM%20currentdateandtime;)

screen shot 2016-07-31 at 4 43 30 pm

### CODE REVIEW

**Comment by DengYiping** [comment]
@jig08 It is a good idea to implement time zone offset also.

**Comment by jig08** [comment]
@DengYiping You meant offset from UTC ? 
If yes, I am not sure it can be done without using any third-party service. In this case, the system date-time have been extracted.

**Comment by sudheesh001** [comment]
The question here would be why would one need this as a JSON when it's easier to obtain from a javascript core functionalities normally, Making a request and then fetching time seems crazy to me. Can you provide a use case

**Comment by jig08** [comment]
@sudheesh001 Was just making a service on lines of others like `location-wise time` for SUSI to resolve issue #748

>To make SUSI answer questions like :
 What's the current time/day/date ?
 What's the current time at <-location-> ?
 What's the time difference between IST and GMT ?
 How many <-hours/minutes/seconds-> is it to 6:00PM in <-location-> ?

Agreed it can be done via Javascript core functionalities though, go ahead and include it in Susi's capabilities :+1:

**Comment by sudheesh001** [comment]
> What's the current time/day/date ?
What's the current time at <-location-> ?
What's the time difference between IST and GMT ?
How many <-hours/minutes/seconds-> is it to 6:00PM in <-location-> ?

We can get this information even from timeanddate.com right ? Why is there the problem ?

**Comment by jig08** [comment]
@sudheesh001 The last time I had done the current date-time using timeanddate.com I had been asked not to use third party service for this. 
Kindly follow up here https://github.com/loklak/loklak_server/pull/715

**Pull request closed without merging**
