### PR TITLE
Extract complete video URLs for Tweets

### PR DESCRIPTION
**Pull request by singhpratyush**
### Short description

Solves #1205.

Related #1171, #1193.

This implementation mimics the video playback flow of mobile react app of Twitter.
1. Extract `BEARER_TOKEN` holding script's URL.
2. Extract guest session token.
3. Extract `BEARER_TOKEN` from URL in 1.
4. Make Twitter API call with the parameters.

Example - 
```json
$ http 'http://127.0.0.1:9000/api/search.json?q=dance+video&source=twitter'
HTTP/1.1 200 OK
Content-Length: 28907
Content-Type: application/json;charset=utf-8
Date: Tue, 30 May 2017 19:40:34 GMT
Expires: Tue, 30 May 2017 19:40:36 GMT
Last-Modified: Tue, 30 May 2017 19:40:34 GMT
Server: Jetty(9.3.z-SNAPSHOT)
Set-Cookie: JSESSIONID=m99m3a8oqnpkkzi9ns2xucz8;Path=/
X-Robots-Tag: noindex,noarchive,nofollow,nosnippet

{
    "readme_0": "THIS JSON IS THE RESULT OF YOUR SEARCH QUERY - THERE IS NO WEB PAGE WHICH SHOWS THE RESULT!",
    "readme_1": "loklak.org is the framework for a message search system, not the portal, read: http://loklak.org/about.html#notasearchportal",
    "readme_2": "This is supposed to be the back-end of a search portal. For the api, see http://loklak.org/api.html",
    "readme_3": "Parameters q=(query), source=(cache|backend|twitter|all), callback=p for jsonp, maximumRecords=(message count), minified=(true|false)",
    "search_metadata": {
        "cache_hits": 0,
        "client": "127.0.0.1",
        "count": "15",
        "count_backend": 0,
        "count_twitter_all": 0,
        "count_twitter_new": 15,
        "filter": "",
        "hits": 15,
        "maximumRecords": "20",
        "period": 7429,
        "query": "dance video",
        "scraperInfo": "local",
        "servicereduction": "false",
        "startRecord": "1",
        "time": 29043
    },
    "statuses": [
        ...
        {
            "audio": [],
            "audio_count": 0,
            "canonical_id": "",
            "classifier_language": "english",
            "classifier_language_probability": 4.53604936798195e-16,
            "created_at": "2017-05-30T19:39:19.000Z",
            "favourites_count": 0,
            "hashtags": [
                "dedication"
            ],
            "hashtags_count": 1,
            "hosts": [
                "pic.twitter.com"
            ],
            "hosts_count": 1,
            "id_str": "869639376531324928",
            "images": [
                "https://pbs.twimg.com/ext_tw_video_thumb/869638871658749954/pu/img/5xW6eHiTJe3x3Z8h.jpg",
                "https://pic.twitter.com/idrtzwp3Nw"
            ],
            "images_count": 2,
            "link": "https://twitter.com/annamorgandance/status/869639376531324928",
            "links": [
                "https://pic.twitter.com/idrtzwp3Nw"
            ],
            "links_count": 1,
            "mentions": [],
            "mentions_count": 0,
            "parent": "",
            "place_context": "ABOUT",
            "place_id": "",
            "place_name": "",
            "provider_type": "SCRAPED",
            "retweet_count": 0,
            "screen_name": "annamorgandance",
            "source_type": "TWITTER",
            "text": "My beaut DDE students Hannah & Carrie who can't resist a quick plié even when at Harry Potter World! #dedication https://pic.twitter.com/idrtzwp3Nw",
            "text_length": 147,
            "timestamp": "2017-05-30T19:40:57.207Z",
            "unshorten": {},
            "user": {
                "appearance_first": "2017-05-30T19:40:57.207Z",
                "appearance_latest": "2017-05-30T19:40:57.207Z",
                "name": "Anna Morgan Dance",
                "profile_image_url_https": "https://pbs.twimg.com/profile_images/868530941580513280/4lC0yEQz_bigger.jpg",
                "screen_name": "annamorgandance",
                "user_id": "745614723148877824"
            },
            "videos": [
                "https://video.twimg.com/ext_tw_video/869638871658749954/pu/vid/480x480/x2lkY3u7inN7g1wD.mp4",
                "https://video.twimg.com/ext_tw_video/869638871658749954/pu/vid/240x240/ANoa8-sHOAm0WJ7S.mp4",
                "https://video.twimg.com/ext_tw_video/869638871658749954/pu/vid/720x720/4W2O7kbxklEZBKyp.mp4",
                "https://video.twimg.com/ext_tw_video/869638871658749954/pu/pl/2l0ByK24IQ2qFM2o.m3u8"
            ],
            "videos_count": 4,
            "without_l_len": 112,
            "without_lu_len": 112,
            "without_luh_len": 100
        },
        ...
        {
            "audio": [],
            "audio_count": 0,
            "canonical_id": "",
            "classifier_language": "english",
            "classifier_language_probability": 6.234241689372219e-15,
            "created_at": "2017-05-30T19:38:39.000Z",
            "favourites_count": 0,
            "hashtags": [],
            "hashtags_count": 0,
            "hosts": [
                "pic.twitter.com"
            ],
            "hosts_count": 1,
            "id_str": "869639212047454210",
            "images": [
                "https://pbs.twimg.com/ext_tw_video_thumb/869639124390625280/pu/img/pJQLGxxK5FMHDRxS.jpg",
                "https://pic.twitter.com/jzgfD4cHos"
            ],
            "images_count": 2,
            "link": "https://twitter.com/prettylittlerem/status/869639212047454210",
            "links": [
                "https://pic.twitter.com/jzgfD4cHos"
            ],
            "links_count": 1,
            "mentions": [
                "missremiashten",
                "breetheunikitty",
                "Elias824",
                "millselle"
            ],
            "mentions_count": 4,
            "parent": "",
            "place_context": "ABOUT",
            "place_id": "",
            "place_name": "",
            "provider_type": "SCRAPED",
            "retweet_count": 0,
            "screen_name": "prettylittlerem",
            "source_type": "TWITTER",
            "text": "THIS DANCE VID WAS AMAZING!!!! TAKE THAT ELLE! @missremiashten @breetheunikitty @Elias824 @millselle https://pic.twitter.com/jzgfD4cHos",
            "text_length": 135,
            "timestamp": "2017-05-30T19:41:02.825Z",
            "unshorten": {},
            "user": {
                "appearance_first": "2017-05-30T19:41:02.825Z",
                "appearance_latest": "2017-05-30T19:41:02.825Z",
                "name": "MISS REMI ASHTEN",
                "profile_image_url_https": "https://pbs.twimg.com/profile_images/848365216027078656/676UcZuR_bigger.jpg",
                "screen_name": "prettylittlerem",
                "user_id": "843235916093231106"
            },
            "videos": [
                "https://video.twimg.com/ext_tw_video/869639124390625280/pu/vid/240x240/zp2c3364FDfSRej7.mp4",
                "https://video.twimg.com/ext_tw_video/869639124390625280/pu/vid/480x480/W7hByhvogFvZlTfZ.mp4",
                "https://video.twimg.com/ext_tw_video/869639124390625280/pu/pl/vg2UXk7rssHUq0Ga.m3u8"
            ],
            "videos_count": 3,
            "without_l_len": 100,
            "without_lu_len": 46,
            "without_luh_len": 46
        },
        ...
```

I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by hemantjadon** [comment]
Hi, @singhpratyush I don't know why this seems to have modified the whole file can you please check?

**Comment by vibhcool** [comment]
@singhpratyush , could you add part of output in gist, and share it's link instead of complete output,
btw good job 👍

**Comment by singhpratyush** [comment]
@vibhcool: Done! Thanks.

@hemantjadon: I'm not sure but I guess it's about the line breaks. In the earlier version, it was `CRLF` and I converted them to `LF`.

**Comment by hemantjadon** [comment]
@singhpratyush Yeah that maybe the case. We can you create a `.editorconfig` the file which will handle such cases, so that such thing doesn't happen and uniformity is maintained throughout with all users. ?

**Comment by singhpratyush** [comment]
@hemantjadon: That would be good, but should go to another PR I guess.

**Comment by vibhcool** [comment]
@singhpratyush , it is difficult to review complete module of 835 lines , please fix the it.

**Comment by singhpratyush** [comment]
@hemantjadon @vibhcool: Done.

**Pull request merged**
