### PR TITLE
#1056 - document how to start contributing

### PR DESCRIPTION
**Pull request by niccokunzmann**
### Short description
I have:
- [X] There is a corresponding issue for this pull request.
- [X] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by yukiisbored** [comment]
The patch is empty?

**Comment by niccokunzmann** [comment]
Hm. I do not know how I can commit an unchanged file. I will look into this..

**Comment by niccokunzmann** [comment]
@yukiisbored I know what happened: The PR #1066 removed the characters which made github recognize the README file as a binary file.
So, Github can not merge because it can not diff.

**Comment by yukiisbored** [comment]
Please also do the same to README.rst.

**Comment by yukiisbored** [comment]
In case you're wondering, README.rst is used by the sphinx documentation site.

**Pull request merged**
