### PR TITLE
Fix 1216: Revert "Installation and Start on a user specified port"

### LINKED ISSUE #1216: Loklak can't be accessed after deploying development on Kubernetes
- Issue type: Bug report

### Short description

The deployment of loklak on Google Cloud Platform with Kubernetes refuses to connect on the public IP address assigned. All the previous steps work fine.

##### Findings
1. The deployment works after reverting 1e0bcd5b353f9f54e65e49979c04e5998f6a3d38.
2. The deployment works after checking out 54841c297197b6ebbcc0671ddcde25fd2f8cb8dc (immediate commit before 1e0bcd5b353f9f54e65e49979c04e5998f6a3d38).

So it is possible that the build broke on that commit.

### Environment

 - Operating system: Google Cloud Platform.
 - Software version: Even with `development`.
 - Software source: Github repository

### Steps to reproduce
1. Follow the steps mentioned in the documentation and deploy on Kubernetes.
2. Try to open the resulting URL.

### Expected behaviour
The website should open.

### Actual behaviour
The website refuses to connect.

### PR DESCRIPTION
**Pull request by singhpratyush**
### Short description

Fixes #1216.
Related #1159.

Kubernetes deployment: http://104.198.183.77/

This reverts commit 1e0bcd5b353f9f54e65e49979c04e5998f6a3d38.

Conflicts (resolved):
	bin/installation.sh
	bin/start.sh

I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by mariobehling** [comment]
Travis is still failing. Please ensure travis is not failing on new commits. This is the responsibility of developers even if travis failures existed beforehand.

Please also ask your co-developers actively by using the "@" feature and ping them on chat if necessary.

**Comment by singhpratyush** [comment]
@mariobehling: The build is passing now. It just needed a restart.

**Comment by mariobehling** [comment]
Thanks.

> Please also ask your co-developers actively by using the "@" feature and ping them on chat if necessary.

**Comment by singhpratyush** [comment]
@vibhcool @djmgit @kavithaenair @hemantjadon @SarishiNoHara @SKrPl: Please review this PR.

**Comment by singhpratyush** [comment]
@hemantjadon: Since we have to make loklak deploy automatically to Google cloud (#1224), we'll have to redeploy anyway.

**Pull request merged**
